---
title: "Tax Evasion and Productivity"
author: "Hans Martinez"
institute: "Western University"
date: today
date-format: long
format:
  beamer:
    aspectratio: 169
    # navigation: horizontal
    include-in-header: header-includes.tex
    template-partials: 
        - before-body.tex
    keep-tex: true
    mainfont: Arial #Times New Roman
  revealjs: 
    slide-number: true
    preview-links: true
    incremental: false
    theme: [simple, theme.scss]
    width: 1260
    height: 700
    embed-resources: true
    navigation-mode: linear
filters: 
  - latex-environment
commands: [sm, tiny, footer, footlineextra]
bibliography:
  - biblio/export.bib
  - biblio/export2.bib
  - biblio/export3.bib
  - biblio/export31072022.bib
  - biblio/b100422.bib
  - biblio/b270123.bib
  - biblio/b100424.bib

---

## Recap {.plain .noframenumbering}

Last meeting: What is an interesting question to wrap up the JMP?

- Counterfactual question: Optimal tax rate


Today:

- SOC of firm's optimization problem
- Functional forms for detection probability and tax evasion cost
- Estimation strategy


[
    [$\hookrightarrow$](#the-model)
]{.footlineextra}


## Introduction

- What's the question?
- Why should you care?

## Contribution

- What do I do?
- How do I do it?

## Overview of Results

- What do I find?
- Why is it important?

## Colombia

<!-- Model -->
{{< include sections/200-model.qmd >}}

## Empirical Strategies

- Testing for the presence of tax evasion by industry
    - Robust to different specifications
- Regression
    - Useful to study tax evasion heterogeneity across firms and over time
- Deconvolution
    - Recover distribution of tax evasion and productivity
    - Estimation of unbiased Production Function

## Data


## Testing

<!-- Fiscal Reform of 1983 -->
<!-- {{< include sections/300-fiscal-reform.qmd >}} -->

<!-- Tax Evasion and Firm Heterogeneity -->
<!-- {{< include sections/400-tax-evasion-het.qmd >}} -->

<!-- ELVIS -->
{{< include sections/620-ELVIS.qmd >}}

<!-- Stage-2 ELVIS preliminary results (moment set A) -->
{{< include sections/650-stage2-prelim-results.qmd >}}

<!-- Counterfactual Question -->
<!-- {{< include sections/500-opt-tax-claude.qmd >}} -->

<!-- Counterfactual Question -->
{{< include sections/600-opt-tax.qmd >}}



<!-- Deconvolving Tax Evasion -->
{{< include sections/700-deconvolving-evasion.qmd >}}

<!-- The Geography of Tax Evasion -->
<!-- {{< include sections/500-geo.qmd >}} -->

<!-- Appendix -->
{{< include sections/900-appendix.qmd >}}

<!-- MSL -->
{{< include sections/610-MSL.qmd >}}

## References

::: {#refs}
:::




