## PRODUCT: Thesis/tables/ch08-cf-revenue.png := counterfactual net sales-tax revenue per firm-year (real pesos) by change
## Delta in the purchases rate, ELVIS interior firms: headline (true materials respond, cf_mresp=1) and robustness (true
## materials fixed), estimate and conservative 95% set; plus the input-demand channel computed from the data alone
## (r = [(1-(1+Delta) tau_P)/(1-tau_P)]^(-1/(1-beta)) depends on no latent): mean change in true materials and the sales tax
## on sales generated by the output response, mean of t1/p_gdp (r^beta - 1).
## Sources: Code/Products/ch08-cf-revenue.csv (written by ch08-cf-revenue-bounds-plot.R from 1651/1652/1653) and the stage-2
## input 1598-stage2-input-designA-interior-plant-k-trim0.005.csv. Break-even bracket (1651, M responds only): only the first
## row whose set excludes zero is shown (Hans 2026-10-07). Formulas: appendix A, @sec-app-cf-implementation.
source("Code/Thesis/001-setup.R")

d <- read.csv(file.path(PRODUCTS_DIR, "ch08-cf-revenue.csv"))
# Break-even of the estimate, true materials respond (Hans 2026-10-10: in the note, so the reader finds the text's number here):
# linear interpolation between the adjacent Delta where the estimate changes sign (as ch08-cf-revenue-bounds-plot.R)
m <- d %>% filter(version == "True materials respond") %>% arrange(Delta)
k <- which(diff(sign(m$rev)) != 0); stopifnot(length(k) == 1)
be <- m$Delta[k] - m$rev[k] * (m$Delta[k + 1] - m$Delta[k]) / (m$rev[k + 1] - m$rev[k])
cat(sprintf("Break-even Delta (true materials respond): %.4f, between %g and %g\n", be, m$Delta[k], m$Delta[k + 1]))
# Hans 2026-10-07: of the bracket rows keep only the first (closest to 0) whose 95% set excludes zero
z0 <- max(d$Delta[d$bracket & d$lo > 0]); stopifnot(is.finite(z0))
d <- d %>% filter(!bracket | Delta == z0)
inp <- read.csv(file.path(PRODUCTS_DIR, "1598-stage2-input-designA-interior-plant-k-trim0.005.csv"))
t1 <- inp$t1 / inp$pgdp; tau <- inp$sales_tax_rate_purchases; b <- inp$beta
chan <- tibble(Delta = sort(unique(d$Delta))) %>% rowwise() %>% mutate(
    r_mean = { r <- ((1 - (1 + Delta) * tau) / (1 - tau))^(-1 / (1 - b)); mean(r) - 1 },
    t1_out = { r <- ((1 - (1 + Delta) * tau) / (1 - tau))^(-1 / (1 - b)); mean(t1 * (r^b - 1)) }) %>% ungroup()

pct <- function(x) ifelse(x == 0, "0", paste0(ifelse(x < 0, "$-$", "+"), sprintf("%g\\%%", abs(100 * x))))
f0 <- function(v) ifelse(v < 0, paste0("$-$", formatC(-v, format = "f", digits = 0, big.mark = ",")),
                         formatC(v, format = "f", digits = 0, big.mark = ","))
set <- function(lo, hi) paste0("[", f0(lo), ", ", f0(hi), "]")
w <- d %>% mutate(v = ifelse(version == "True materials respond", "mr", "fx")) %>%
    select(v, Delta, rev, lo, hi) %>% pivot_wider(names_from = v, values_from = c(rev, lo, hi)) %>%
    left_join(chan, by = "Delta") %>% arrange(Delta)
br_D <- d$Delta[d$bracket]   # break-even bracket rows: true materials respond only
stopifnot(!anyNA(w$rev_mr), all(is.na(w$rev_fx) == w$Delta %in% br_D))
tbl <- w %>% transmute(
    `$\\Delta$` = pct(Delta),
    `Estimate` = f0(rev_mr), `95\\% set` = set(lo_mr, hi_mr),
    `Estimate ` = ifelse(is.na(rev_fx), "", f0(rev_fx)), `95\\% set ` = ifelse(is.na(rev_fx), "", set(lo_fx, hi_fx)),
    `True $M$` = ifelse(Delta == 0, "0", paste0(ifelse(r_mean < 0, "$-$", "+"), sprintf("%.1f\\%%", abs(100 * r_mean)))),
    `Gross revenue` = f0(t1_out))
print(tbl)

crit <- d$crit[1]
tt_obj <- tt(tbl, width = c(0.5, 0.7, 1.3, 0.7, 1.3, 0.7, 1.2), notes = paste0(
    "Real pesos per firm-year, ELVIS interior firms (12,050 firm-years). Net sales-tax revenue = gross sales-tax revenue minus ",
    "expected sales-tax refunds. 95\\% set: conservative test, $TS\\le\\chi^2_{18,.95}=", sprintf("%.2f", crit), "$. ",
    "True materials respond: the materials first-order condition with the two tax rates, capital, labour and productivity fixed. ",
    "True $M$: mean change in true materials; gross revenue: mean change in gross sales-tax revenue from the output response. ",
    "Both come from the data alone. ", pct(z0), " is the smallest cut, on a finer grid, whose 95\\% set excludes zero ",
    "(true materials respond only). With true materials responding, the estimate breaks even at a cut of about ",
    sprintf("%.0f", abs(100 * be)), "\\%, interpolating linearly between ", pct(m$Delta[k]), " and ", pct(m$Delta[k + 1]), ".")) |>
    group_tt(j = list("True materials respond" = 2:3, "True materials fixed" = 4:5, "Materials channel" = 6:7)) |>
    style_tt(i = which(w$Delta == 0), background = "#f2f2f2") |>
    style_tt(i = "notes", fontsize = 0.8)

render_thesis_table(tt_obj, "ch08-cf-revenue")
