# Strategies to present results

Objective: Choosing relevant industries where tax evesion is significant to show effects on PF coefficients and estimates of tax evasion. The larger the most surprising, the better. 

Problem: The list should not appear cherrypicked. 

Industries I would like to display in the paper:

Significant evasion:

- 322 (Maybe: results are huge, why?)
- 331 Wood Products, no furniture
- 321 Textiles
- 342 Printing and publishing (books were exempt)
- 313 Beverages (Food industries exempt but not drinks)
- 390 Other Mfg Inds

Low incentives:
- 311 Food industries (exempt)
- 312 
- 323 Leather Products, high share of exporters


## Strategy 1: Statistical test as a tool to guide practitioners in investigating Tax Evasion

Provide a statistical test as a guiding tool to select industries to investigate:

Why? It is not obvious where to look for tax evasion. Although theory provides hints of where to look, 

1. firms actively hide fraudulent behavior, ex-ante we do not know if tax evasion could be identified from data, and 
2. other taxes ignored in the theoretical model might generate conflicting incentives with the model, so that the dominant effect from the model might be ambiguous.

## Strategy 2: Groups of industries

Take groups of industries. Take the three groups with more spending per industry.

Group 1:

- 321 Textiles
- 322 Wearing apparel
- 323 Leather Products
- 324 Footwear

While 321, 322, and 324 are statistically significant, 323 is not. This makes sense because 323 is the largest exporter, highest share of sales are exports and greater number of firms exporting 10 percent or more of their sales.

Group 2:

- 311 
- 312 
- 313 

In contrast to 311 and 312, 313 is not exempt and the evidence is statistically significant

Group 3:

- 331 Wood Products except furniture
- 332 Wood Furniture

Both industries consume and sell their products locally (low shares of exports and imports) and one third of their joint consumtion comes from forestry, which is exempt of sales tax. For industry 331, the large share of primary goods probably leads to a high effective sales tax rate because we expect there might not be many more other inputs needed in the production process. Hence,firms in this industry might face high incentives to overreport their non-primary inputs to evade sales taxes.

However, for firms in industry 332, even though they also consume a large share of primary goods, they also consume a more diverse set of inputs to produce the wood furniture, such as textiles, chemicals, foam cushions, and others. Because of this wide range of inputs, the sales tax paid for their inputs might be high leading to a low effective sales rate and hence, low incentives to evade taxes.
