## TODO {-}

- JMP Structure:
  - Introduction
  - Literature Review
  - Motivating model
    - Key assumptions:
      - Firms artificially inflate material inputs to reduce sales tax liability (VAT type) and CIT (increasing costs reduces taxable income)
      - Detection probability independent of input choice
      - Corporations do not evade taxes through input overreporting because the marginal economic cost of evasion exceeds the marginal benefit for any non-zero level of evasion
  - Testing for tax evasion through input overreporting
  - Why? Testing is robust to relaxing the the assumption of the probability of detection being independent of input choice
    - In Colombia: By industry
      - Bootstrap
      - Randomization inference
    - Other countries (Spain, India, Chile)
  - Empirical approach: Heterogeneity in tax evasion 
    - Across firms: Who evades more?
      - in COL: Small firms, exporters, importers, by J.O.
      - Other countries (?): Spain, India
    - Across Time: Exploiting tax policy changes in Colombia
      - Triple difference identification strategy
  - Deconvolution approach:
    - NP deconvolution of densities:
      - tax evasion
      - productivity
    - Countries: Colombia (main), Chile, Spain, and India
    - Application: 
      - Compare Productivity and PF estimates with naive estimation
      - Back of envelope estimates of tax revenue losses due to evasion
      - Misallocation measure
  - Possible extensions:
    - Estimate detection probability/tax evasion cost function from unused FOC
    - Non-random auditing from tax authority
    - More flexible functional forms for production function (Translog)
    - More flexible process for productivity (ELVIS)


- Other Data: Spain, India, and Chile
  - All include Type of Firm (Juridical Organization)
  - Spain data needs to be bought
  - Indian data is publicly available
    - Need to download and consolidate
  - Chile data is ready
  

- Summarize main points of Lit Review



