## Notes

### Next steps

- Estimate parametric deconvolution for Colombian data. Use industries that paid the least taxes in 1981?
- Model: polish with comments from Javier and Chong
- Model: Add the continuous case
- Model: send to Rory for feedback
- Check if Colombian data match predictions from the model about the distribution of the firm's income
- Check out Chilenean data:
    - What's k, l, m?
    - What information is there about taxes?


## March 21, 2024

Feedback:
- Corporations might have different technologies than the rest of the firms
- What are corporations, proprietorships, limited partnerships? How are firms choosing their legal entity?
- Transition matrix between the different juridical organizations
- left-hand side equation statistics
- Can I use the changes in policy to support the assumption that corporations have similar technologies to other firms
- An issue with the evidence I showed is it is too noisy.

Comments:
- The current state of affairs is that if corporations do have different technologies they are being captured as productivity. Econometricians estimate productivity not controlling for juridical organization.
- We can write up a model where firms select their juridical organization at the beginning of each period based on their expected future stream of productivity shocks. Firms will choose to be corporations if the expected profits are greater than staying as limited partnerships. But what are the incentives for being a corporation? Why would firms reveal their superior technology by choosing to be a corporation if they have to pay higher CIT as corporations? It is a decision about getting capital. To increase their capital past a certain level, firms have to incorporate.
- The three relevant types of juridical organizations are proprietorships, limited liability companies, and corporations. Proprietorships are individuals owning a company under their name. They are subject to individual income taxes. They avoid double taxation but are subject to high wealth risk. Limited partnerships are associations of capital, their shares cannot be traded and they are limited to twenty shareholders. Limited partnerships enjoy limited liability. Limited liability companies and partnerships were subject to Corporate Income Tax of 20%. Corporations are associations of capital, tradable shares, subject to 40% CIT.


### Corporations

- Corporation (Sociedad Anonima): typical association of capital; it is the counterpart of the US corporation. Corporations are subject to the Superintendent of Corporations and are closely supervised, being required, for example, to have an auditor and to maintain a legal reserve. 

A corporation is a commercial entity whose capital is divided into tradable shares of equal value. The capital of a corporation is provided by the shareholders (no less than 5 shareholders). Shareholders's liability is limited to the capital contributed.

- Limited Stock Partnership (Joint Stock Co. in Data: *Sociedad en Comandita por Acciones*): Limited partnerships with the partnership interests represented by shares of stocks and taxed as corporations (CIT). The capital of this company is divided into shares of equal nominal value, either nominative or bearer. The issuance, placement, issuance of securities, and negotiation of shares are subject to the provisions applicable to the corporation. It cannot be formed or operated with fewer than 5 shareholders. The firm name is treated similarly to that of a general partnership, but with the addition of the words "Sociedad Comandita por Acciones" or its abbreviation "SCA"

### Limited Liability Company

- Limited Liability Company (Limited Partnership in Data) (*Sociedad de responsabilidad limitada*; limited liability company in Fiscal Survey of Colombia): Formed by two or more partners (not exceeding 25), whose contributions do not represent freely negotiable securities or titles (non-tradable shares). The partners are jointly liable for the partnership's obligations up to the amount of their contributions. They conduct their activities under a firm name or objective denomination to which the word "Limited" or its abbreviation "Ltd." is added in any case.

The limited liability company is quite important (1960s) in Colombia. It combines certain features of a corporation and a partnership. It is organized in the same manner as a general partnership but with the additional requirement that the articles of association must indicate that the personal liability of the partners is limited to the capital contributed. The limited liability company offers some advantages as compared to a corporation, chiefly, the lower cost of organization and taxation (until the 1980s reforms) and comparative freedom of operation. Under Colombian law, the limited liability company is an association of persons, not of capital, and it is not subject to the superintendent of Corporations unless more than one-third is owned by a corporation.

### Partnerships

- General Partnerships (*Sociedad Collectiva*, Collective in the data): Comprises two or more individuals who associate under a firm name. All partners are jointly and severally liable for the partnership's operations. The firm name may consist of the names of all the partners, or some of them, followed by the words "and Associates," "Company," "Brothers," "and Sons," "Successors," or other similar terms.

- *de Facto* Partnerships (*sociedades de hecho*, De Facto Corporation in dataset): These are partnerships that are not established by public deed. As such, they are not legal entities, and consequently, any rights acquired and obligations undertaken are understood to be in favor of or borne by all the de facto partners.

- Ordinary Limited Partnerships (*Sociedad en Comandita Simple*, Joint Partnership in the data):  Comprises one or more managing partners who are jointly and severally liable, and one or more limited partners whose liability is limited to their respective contributions. The firm name shall consist of the full name or surnames of one or more managing partners, followed by the words "Sociedad en Comandita" or "S. en C."

### Proprietorships

Proprietorships appear as a juridical organization in the data but it can have two definitions according to the survey documents of 1992-1994.

- Natural Person or Individual Proprietorship (*Persona natural o propiedad individual*): A legal entity with the capacity to acquire and exercise rights, to enter into and fulfill individual obligations arising from their actions.

- Sole Proprietorship (*Empresa unipersonal*): A legal entity formed by the presence of a natural or legal person who allocates part of their assets for the conduct of one or more commercial activities.

### Others

These juridical organizations are not described in the Fiscual Survey, but they are found in the data.

- Cooperative and Religious Community. Type of Solidarity Economy Organization (*Organizacion de Economía Solidaria*): Primarily characterized by the establishment of an associative bond founded on the principles and objectives outlined in Articles 4 and 5 of Law 454/98. Thus, they must include in their statutes and operations democratic participation and non-profit motives, meaning 1) the establishment of the irrevocable nature of social reserves and, in case of liquidation, the distribution of remaining assets. 2) the allocation of their surpluses to provide social services, to grow their reserves and funds, and to reimburse their members part of these surpluses in proportion to their use of the services or participation in the work of the enterprise, without prejudice to the amortization of contributions and their retention at their legal value. This includes cooperatives, pre-cooperatives, auxiliary institutions of solidarity economy, cooperative public administration service companies, employee funds, worker cooperatives, mutual associations, solidarity health companies, community enterprises, federations and confederations, associations, and associative labor companies.

- Official entity. State Industrial and Commercial Enterprise (*Empresa Industrial y Comercial del Estado*): These are organizations established by law or authorized by it to engage in industrial or commercial activities, with independent capital formed with public assets or funds, the proceeds of which come from taxes, fees, or contributions with special purposes.


## Summary

| Juridical Organization | CIT | Liability | Capital | Owners |
|:----------------------:|:---:|:---------:|:-------:|:----------:|
| Corporations           | 40% | Limited to capital participation | Tradable capital shares | $N\ge5$ |
| Limited Liability Company | 20% | Limited to capital participation | Non-tradable capital shares | $2\le N \le 20 (25)$ |
| Partnerships | 20% | Full | Not a capital association | $N\ge2$ |
| Proprietorship | Individual Income Tax | Full | Owner | $N=1$ |

## Model of firm growth

A limited liability company looking to acquire more capital had three options. First, partners can increase their capital participation, using personal wealth or through a bank credit. This option however will increase the partners' liability. The more capital I bring the greater my liability is. Second, the LLC might increase its capital by inviting additional partners. As the firm increases its capital, inviting more partners will become more difficult. The funding partners risk losing control of their firm, as more people participate in the firm's management and decision-making. Third, the firm can incorporate. This will bring capital to the firm. Anyone in the market for the shares of the firm can participate. Shares can be traded. A CEO reporting to the shareholders might be appointed. Liability is limited to shares.

The decision to incorporate is a decision on how to acquire capital. Firms still need to consider the stream of future productivity shocks, but the decision also depends on other unobservables such as risk-aversion (increasing the partners' liability), the partners' ability to convince more partners to join the LLC, and preferences over the control of the firm's management.

The increase of 20 pp in the CIT rate between LLC and Corporations might have deterred firm growth. The CIT was homogenized to 30% in 1986.

## How was capital taxed in Colombia?

- Net wealth tax
- used in presumptive income estimations
- rents of capital were taxed, how? Income


## Arguments in favor of single common production technology

- Evasion technology vs. production technology. Take the face value of the regressions and assume, without conceding, that corporations have different technologies. This will imply that corporations have technologies that are consistently 15% more productive than non-corporations regardless of the industry. In other words, it does not matter if the firms produce canned food, shoes or furniture, corporations have technologies consistently more productive. However, this is difficult to believe because there could be industries in which such an improvement in technology is difficult to imagine. For example, coffee grain mills (food products), steel foundries (steel basic products), plastic molding and extrusion (plastic products), or cement (non-metallic mineral products). 

However, these cross-sectional differences across industries could be better explained by the evasion technology. We would expect the evasion technology to be the same across industries. It does not matter what I produce and what technology my firm employs, to overreport inputs all that is needed is a fake invoice. 

- The current state of affairs. Researchers are not separating firms into juridical organizations. Differences in technology within an industry are being captured as persistent positive productivity shocks. In this line of thought, we can design a model in which firms self-select into corporations based on the expected stream of future productivity shocks. If this model is correct then my identification strategy is valid. If the model is not correct and corporations have different technologies then researchers can still identify the most productive firms — it's just a ranking. However, my identification strategy will mislabel the difference between corporation and non-corporation technology as evasion. This argument does not work. It's not compelling. 