## Introduction {-}

Corporate tax evasion through cost overreporting spreads internationally causing governments significant tax revenue losses. Detecting and measuring the magnitude of tax evasion remains a challenge, even for the few studies on overreporting where researchers can exploit administrative data. Moreover, if this evasion strategy accounts for economic losses as large as reported, then cost overreporting might bias estimates of production functions, especially productivity. This paper addresses both issues. I first provide a novel strategy to estimate cost overreporting using commonly available firm-level data. I then formally show that ignoring cost overreporting leads to downward biased productivity estimates. Finally, I demonstrate how to recover productivity in the presence of tax evasion.

Cost overreporting arises when firms acquire false invoices to claim additional tax deductions on value-added and corporate income taxes. According to the OECD's document @OECD2017, cost overreporting — also known as "fake invoicing", "ghost firms", "invoice mills", or "missing traders"— permeates internationally reaching Latin America, Eastern Europe, Asia, and Africa. Cost overreporting reportedly generated annual tax revenue losses amounting to non-trivial shares of GDP in countries such as Poland, 6%; Chile, 0.2%; Colombia, 0.2%; and Mexico, 0.03%. Recent evidence from Ecuador @Carrillo2022 shows that contrary to current belief, cost overreporting is widespread across firms —not limited to small, semi-formal firms— and quantitatively large. \fxnote*{how does it compare to other forms of tax evasion?}

The evidence from Ecuador also shows that big firms do not overreport inputs. This is unsurprising for several reasons. First, a large firm arguably draws more attention from the tax authority. Given its limited resources, the government optimizes its expected revenues by targeting the firms with the higher potential tax recovery, the few big ones. Second, the cost of being caught cheating is potentially higher for big firms. Large firms are likely to participate in international markets. A tax evasion scandal in Colombia, for example, might affect US sales. Finally, big firms potentially have more sophisticated strategies for tax evasion [e.g., profit shifting @Bustos2022].

Despite its relevance, cost overreporting has been mostly overlooked by the literature. On one hand, the few studies on this evasion strategy exploit detailed administrative data [@Zumaya2021; @Carrillo2022]. Government tax authorities restrict access to administrative data because of firms' confidentiality concerns. On the other hand, to the best of my knowledge, no study has attempted to structurally identify cost overreporting. Unlike the case of individuals [@Pissarides1989; @Paulus2015], when it comes to corporate tax evasion, researchers have to account for an additional source of unobserved heterogeneity, productivity. Why? Because cost overreporting might be naively quantified as low productivity. Intuitively, for a given output level, high input utilization by a firm could be explained by either the amount of input the firm overreports to evade taxes or by a low productivity shock.

To address this gap in the literature, first I formally show that ignoring tax evasion leads to downwardly biased productivity estimates. I then provide a new estimation strategy, requiring only commonly available firm-level data, to jointly recover the densities of tax evasion and productivity. The intuition works as follows. In the absence of tax evasion, the first-order conditions of the firms' cost-minimization problem inform about a common technology, the production function. Consequently, in the presence of cost overreporting, deviations from this common technology identify tax evasion up to the current-period output shock. Then, from the subset of non-overreporting firms, the strategy identifies the production function parameters and the density of the output shock. Finally, using deconvolution techniques, I jointly recover the distributions of tax evasion and productivity. I also estimate how tax evasion evolves with productivity, in other words, their joint distribution.

Using firm-level data from Ecuador, Colombia, Chile, and Mexico, the estimates show that ...

\begin{anfxnote*}{Remove}

I formally show that ignoring tax evasion leads to biased estimates of productivity, which can be significant considering cost overreporting is widespread and quantitatively large. In the proxy variable literature, productivity is measured as the residual of a production function, where the output is a function of the inputs. A key assumption is that input demand is strictly monotonic on the productivity [@Gandhi2020; @Ackerberg2015; @Levinsohn2003]. In other words, we expect highly productive firms will use fewer inputs and produce more output. When firms overreport their costs (inputs) to reduce their tax liabilities, their reported inputs are higher than their actual utilization, resulting in lower productivity estimates.

Tax evasion through cost overreporting has been largely overlooked by the literature, though; most recent studies focus on revenue underreporting.

Despite its relevance, detecting and measuring tax evasion —through cost overreporting or otherwise— remains a non-trivial task even for governments with detailed administrative data; mainly because of firms' —and individuals'— incentives to avoid getting caught. Direct empirical measures are mostly unreliable because firms and individuals have incentives to conceal their behavior [@Slemrod2019]. Hence, it is unlikely that evasion would be truthfully reported in surveys, for instance. Indirect structural measures have had some degree of success in the case of individual income tax evasion [@Pissarides1989], but in the case of corporate tax evasion researchers must account for an additional latent variable, the productivity of firms. The reason is that tax evasion might be naively quantified as low productivity. Intuitively, for a given level of output, high input utilization by a firm could be explained by either the amount of input the firm overreports to evade taxes or by a low productivity shock. In certain countries, governments take advantage of the different sources of administrative data. For example, in Ecuador, the tax authority uses third-party information on reported corporate taxes to detect evasion through revenue underreporting [@Carrillo2017]. However, access to this type of administrative data is generally restricted for most researchers.

Despite the vast efforts of the literature, measuring tax evasion remains a non-trivial task[^measure].

[^measure]: The challenge is to obtain reliable data. Practitioners usually have to undergo time- and resource-consuming processes to access or collect data; for example, by requesting access to government administrative data or by collecting their own through surveys or experiments.

Tax evasion is a significant concern for developing and developed countries[^wide]. 

[^wide]: Tax evasion has been a long-standing concern for developing countries, but since the 2008 economic crisis, it has also been of increasing importance for developed countries [@Slemrod2019].


Having productivity estimates could potentially help, however, tax evasion has not been satisfactorily addressed in the estimation of productivity. I show that ignoring tax evasion leads to biased estimates of productivity. To address this gap in the literature, I provide a new estimation strategy to recover tax evasion and productivity using commonly available data. 

Indirect structural attempts to estimate corporate tax evasion have to account for the productivity of the firms. The reason is that low productivity might be naively quantified as tax evasion. Consider the case in which firms overreport input expenses to reduce their profits to evade taxes. A practitioner with output and input data might conclude that output is a function of inputs, thus it can be considered a second measure. She might try to recover true inputs and get an estimate of tax evasion by the difference between reported and true inputs. However, for a given level of output, high input utilization by a firm could be explained by either the amount of input the firm overreports to evade taxes or by its low productivity.

Firm-level estimates of productivity could be helpful to measure tax evasion, however, tax evasion has not been satisfactorily addressed in the estimation of productivity by the literature. The literature has coped with tax evasion by treating it as a classical measurement error [e.g., @Blalock2004, p.204]. In other words, it has been assumed that tax-evasion misreporting has zero mean —some firms under-report and others over-report so that the misreporting does not bias the estimates of interest— and this misreporting is independent of everything else, including the attributes of the firms. However, the classical measurement error argument is inconsistent with economic intuition[^econ-int]. 

[^econ-int]: Economic intuition will inform us that systematic misreporting due to tax evasion should lead firms to decrease profits by either underreporting sales or overreporting costs. Put differently, there's no economic incentive for firms to go the other direction —overreporting sales or underreporting input expenses— and artificially increase their profits. An artificial increment of profits will increase the tax liabilities of the firm and decrease their after-tax real profits. Therefore, it is unlikely that tax evasion is mean zero. Economic intuition will also point out that the degree of misreporting is likely to vary across firms depending on the characteristics of the firms, e.g., age, size, owner's risk aversion, etc.
    
The contribution to the tax evasion literature is two-fold: (1) I provide an estimation strategy using commonly available data, and (2) the method identifies tax evasion through cost overreporting, an overlooked by the literature but relevant phenomenon. The contribution to the productivity literature is to show that ignoring tax evasion leads to biased estimates and to provide a method to recover the productivity density in the presence of input overreporting.

Why do we care about productivity measurement bias due to tax evasion? First, it might help explain part of the productivity gap puzzle. Economists have found *enormous and consistent* productivity differences across producers [@Syverson2011]. We still don't know how much of this productivity gap —the difference between the lower and higher percentiles of the distribution— tax evasion can explain. Second, it should be considered in the design of public policies aiming at reducing resource misallocations. Aggregate productivity —and, thus, the economic growth of a country and the welfare of its citizens— depends on the efficient allocation of its inputs among its firms. Ideally, resources should be allocated to the most productive firms. Additionally, it is not necessarily the case that firms with the highest incentives to evade taxes are always the lowest productive. The incentives depend on the tax system. For example, in countries where a profit threshold determines different tax rates, the firms near the threshold are the ones with the highest incentives to misreport, but the threshold might be completely unrelated to productivity. Therefore, firm-level productivity estimates adjusted by tax evasion misreporting might inform better the design of public policies aiming at an efficient reallocation of resources to boost economic growth.

Moreover, accounting for tax evasion in estimating and measuring firm-level productivity is particularly significant for developing countries. This is the case because tax evasion is likely to be higher in low- and middle-income countries[^infor], and because the productivity gap in these countries is wider —wider productivity gaps are associated with higher resource misallocations. For example, recent estimates of non-detected tax evasion are up to \$10 billion USD per year in Mexico [@Zumaya2021], approximately 1% of the country's GDP. Furthermore, some studies argue that input misallocation —implied by a wider productivity gap— explains a significant part of the differences in income per capita between developed and developing countries [@Syverson2011; @Levy2018]. For instance, evidence from Colombia suggests that labor and financial policy reforms during the 1990s aimed at reallocating away from low- and towards high-productivity firms —effectively reducing the productivity gap— resulted in a higher aggregate productivity [@Eslava2004].

[^infor]: Informality —the extreme form of tax evasion— is larger in developing countries [@Loayza2006; @LaPorta2014].

The main challenge of dealing with tax evasion is that it is hidden by nature, for that reason, 


So, then, in this paper, I ask, 

> can we recover unbiased productivity estimates at the firm level using a gross-output production function in the presence of systematic misreporting due to tax evasion?
> if so, what is the magnitude of this bias, in particular for developing countries?
> given that different tax systems —rates, rules and enforcement procedures— generate different tax evasion incentives, how does the producitivity bias vary according to different tax systems? 
> how much of the productivity gap can tax evasion explain within a country and across countries?

To answer these questions, this paper studies productivity at the establishment level for Mexican and Colombian firms accounting for tax evasion. I employ data from a sample of anonymized firms' tax filings and INEGI's EAIM annual production survey, in the case of Mexico. For Colombia, I use the EAM annual survey on manufacturing firms. In the estimation framework, I jointly model the firm-level productivity and the tax evasion, allowing for classical measurement error. The key identifying assumption is that while tax evasion depends on the expected return to cheating, productivity follows a Markov process, and measurement error is uncorrelated with inputs and across time. In turn, the expected returns to cheating depend on the firm's characteristics[^mkt]. In particular, larger firms are less likely to underreport inputs because of their higher cheating cost, their higher probability to be anonymously denounced by an employee, and their access to complex tools to legally \emph{avoid} taxes[^avoid].

[^mkt]: Tax evasion might also depend on the firm's market characteristics, e.g., market concentration, end-consumer vs. intermediate goods market, etc.

[^avoid]:  I follow the literature by referring to evasion as illegal actions to reduce tax liability, while avoidance refers to legal actions to reduce tax.

By jointly modeling tax evasion and productivity, this paper departs from the literature in estimating a latent variable that follows an incentive constraint (IC) —tax compliance—, and in focusing on the productivity bias —rather than on an input's coefficient. Recent work has studied the effect of measurement error in capital inputs on production function estimation. Their approach has been using an IV [@Collard2020] or a centering condition *à la* @Hu2008 (Charlotte's JMP). However, systematic misreporting is different from measurement error in that it goes only one way and it follows an IC, as discussed above. Likewise, because capital is not a flexible input[^flex], the focus of these papers is on the effect of the marginal return to capital coefficient rather than on the effect on productivity estimates.

[^flex]: In the literature, a flexible input is neither dynamic —current input choice depends on its lagged value—, nor predetermined —completely defined in the past.

Moreover, I focus on gross-output production functions, as opposed to value-added, to reduce the noise that might be introduced by firms cheating also on prices. Besides the fact that prices are an equilibrium object and might be affected by demand also —and not only by supply—, firms might also artificially increase the price of inputs or reduce the price of sales to reduce declared profits. Then, in that sense, the tax-evasion bias magnitude of productivity estimates obtained through a value-added production function would be greater than through the gross-output production function. In the latter, only the price of the flexible input —intermediates—, and the output sale price enter through the first-order conditions (FOC) of the profit maximization problem of the firm[^cros_d]. In contrast, the prices of the non-flexible inputs, —capital and labor—, might introduce noise in the case of the value-added production function. \fxnote{tax evasion underreporting sales: use firms that sell to other firms because of opposite incentives in contrast to firm-end consumer sales. Unskilled labor might be flexible but it's the least productive, so less damage.}

[^cros_d]: If the cross-derivative of the flexible input with respect to the non-flexible inputs is not zero, then systematic misreporting in the non-flexible inputs will also affect productivity.

\end{anfxnote*}

