
## Colombia's fiscal reforms of 1983, 1986, and 1990 {.appendix -}

The 1983 reform tried to increase the country's income tax and reactivate the economy. The 1986 reform attempted to reduce evasion, among other things. The 1990 reform took place during the process of commercial opening. It had the objective of developing the capital market and incentivizing the repatriation of foreign capital.


### 1983 Reform

**Corporate profit tax (impuesto de la renta):** In 1983, Colombia reduced the maximum corporate tax rate from 56% to 49%. The progressive tax schedule went from 11.5% to 49%. However, the base of the taxpayers was increased.

**VAT (IVA)**: Increased from 6% to 10%. The 1983 reform set the VAT on national vehicles between 25-30%, depending on the motor. The motorcycles' VAT rate was set at 20%.

The tax authorities focused on the 5% of the big taxpayers that constituted 80% of the country's tax revenue.

### 1986 Reform

**Corporate profit tax**: In 1986, Colombia set the corporate max tax rate at 30% starting in 1989. To ease the transition, they set tax rates of 33%, 32%, and 31% for 1986, 1987, and 1988.

The reform relocated the tax collection and reception of tax reports to the banking system. Likewise, the 1986 reform increased the control over the big taxpayers.

### 1990 Reform

Corporate income tax: among other things, the foreign investment tax rates were reduced. Also, the reform reduced the base of the taxpayers obligated to file tax reports.

VAT was increased from 10% to 12%. In addition, several exceptions were eliminated, so the basket of taxed goods increased.

Import taxes were reduced and some goods were exempted.