## Revenue misreporting

Firms might also evade CIT and VAT by underreporting their revenues. Upstream firms, however, are less likely to engage in this kind of evasion [@Almunia2018]. Manufacturing firms in Colombia were mostly upstream; only 13% of their sales were direct final consumers, according to a sample of firms surveyed in 1984 [@Perry1990]. 

As robustness checks, I can identify industries whose sale shares directed to final consumers are negligible from this historical document [@tbl-1984-manu-sales]. 

| SIC    | Total no. of firms | % to retailers | % to public | % retailers and public combined | % government | % wholesalers |
|--------|-------------------:|---------------:|------------:|--------------------------------:|-------------:|--------------:|
| 312    | 25                 | 24.16          | 15.72       | 39.88                           | 1.20         | 58.92         |
| 313    | 3                  | -              | 29.33       | 29.33                           | 0            | 70.67         |
| 321    | 8                  | 15.06          | 0.11        | 15.17                           | 1.17         | 83.67         |
| 322    | 2                  | 52.92          | 14.58       | 67.50                           | 0            | 32.50         |
| 324    | 5                  | 45.00          | 4.00        | 49.00                           | 0            | 51.00         |
| 332    | 8                  | 10.85          | 20.15       | 31.00                           | 5.92         | 63.08         |
| 341    | 6                  | 5.00           | 0           | 5.00                            | 0            | 95.00         |
| 342    | 9                  | 19.44          | 34.44       | 53.89                           | 7.22         | 38.89         |
| 351    | 5                  | 15.20          | 6.00        | 21.20                           | 2.80         | 76.00         |
| 352    | 8                  | 37.81          | 5.50        | 43.31                           | 4.47         | 52.22         |
| 353    | 3                  | 5.67           | 5.00        | 10.67                           | 0            | 89.33         |
| 355    | 5                  | 21.00          | 0           | 21.00                           | 0            | 79.00         |
| 362    | 1                  | 10.00          | 0           | 10.00                           | 0            | 90.00         |
| 369    | 8                  | 21.25          | 28.75       | 50.00                           | 12.88        | 37.13         |
| 372    | 3                  | 10.00          | 0           | 10.00                           | 1.67         | 88.33         |
| 381    | 22                 | 12.41          | 14.73       | 27.14                           | 2.50         | 70.36         |
| 382    | 20                 | 11.20          | 30.00       | 41.20                           | 9.00         | 49.80         |
| 383    | 15                 | 13.87          | 7.13        | 21.00                           | 9.07         | 69.93         |
| 384    | 7                  | 0              | 34.57       | 34.57                           | 0            | 65.43         |
| 390    | 3                  | 58.00          | 3.33        | 61.33                           | 3.33         | 35.33         |
| 356    | 11                 | 15.55          | 6.00        | 21.55                           | 3.18         | 75.27         |
: Distribution of Sales from Manufacturing Firms, by type of Purchaser (in percentage) [@Perry1990] {#tbl-1984-manu-sales}


In addition, the SIC definitions provide useful information about the nature of the products whether they are for final consumption or intermediate inputs for other industries. For example, the definition of industry `371` Iron and Steel Basic Industries includes the note "[...]. The foundries included here are [..] primarily engaged in manufacturing castings and forgings to sale to others."

### Large Taxpayers Unit in Spain

I argue that upstream firms are likely to misreport only inputs but not revenue. Although @Almunia2018 conclude that Spanish firms misreport both revenue and inputs, the authors do not discard the case where firms bunch below the LTU threshold, report their true output, and only misreport inputs. While buying firms have incentives to overreport input expenses, selling (upstream) firms have incentives to underreport sales. Hence, due to opposite incentives with their clients, upstream firms might find it hard to underreport their revenue. If the expected benefits of staying below the LTU threshold and evading taxes outweigh the opportunity costs of forgone production and the expected cost of evasion, upstream firms are likely to bunch below the LTU threshold —by reducing their output— and misreport their inputs.

Unlike downstream firms, upstream firms are less likely to underreport their revenue. To underreport revenue, selling firms need to coordinate with the buying party. The buying party must agree to not require an invoice, to avoid leaving a paper trail. This is likely to happen with downstream firms —firms that sell to final customers. Customers might get a discount to accept cooperating with downstream firms. However, with upstream firms —firms selling to other firms—, this is unlikely the case. The reason is that, unlike final customers, buying firms have incentives to overreport their input consumption and reduce their VAT and CIT.

The authors do find upstream firms bunching below the LTU threshold. Upstream firm bunching is lower than for downstream firms. This makes sense because downstream firms do not have to consider in their decision the additional opportunity cost of forgone production. This additional cost might render bunching less profitable for upstream firms leading to a lower number of firms reducing their output to stay below the LTU threshold and evade taxes.

Moreover, the authors show evidence suggesting upstream firms misreport inputs. In the online appendix, the authors show that the ratios of intermediate expenses over revenue and labor expenses over revenue of wholesale (upstream) and retail (downstream) firms follow what they identify as general evasion patterns. The intermediates' cost share of revenue follows an upward-sloping trend and then drops off at the cutoff. The labor's cost share of revenue follows a downward-sloping trend and then jumps up at the cutoff.

### How to Deal with Revenue Underreporting

Under CD production function and revenue underreporting, $Y_{it}=Y^*_{it}\exp^{-u_{it}}$, @eq-foc-cd becomes

$$
    \ln\left(\frac{\rho_t M^*_{it}}{P_{t}Y^*_{it}}\right)+e_{it}+u_{it}=\ln D^{\mathcal{E}}- \varepsilon^Y_{it}
$$ {#eq-rev-under}

Note that both, revenue underreporting and input overreporting, artificially increase the input cost share of revenue.

It is natural to extend \ref{ass-non-ev} to revenue underreporting. Non-evaders will also not underreport revenue because of the same reasons incentivizing them to not overreport inputs.

Moreover, as discussed previously, upstream firms are likely to find it harder than downstream firms to underreport revenue. Assuming the evasion technology is the same across industries, we can separate output from input misreporting.

Formally,

::: {.Assumption #ass-non-ev-2}
#### Non-Evaders II
The subset of firms $\theta_i\in\Theta^{NE}\subset \Theta$ do not evade taxes by underreporting revenue or overreporting inputs.
:::

::: {.Assumption #ass-upstream}
#### Upstream Firms
Upstream firms $\theta_i\in\Theta^{UP}\subset \Theta$ do not evade taxes by underreporting revenue but do evade taxes by overreporting inputs.
:::

::: {.Assumption #ass-upstream}
#### Misreporting Technology
Misreporting technology is the same across industries.
:::
