## Intermediate Inputs {#sec-inter}

What are intermediate inputs? Intermediate inputs are flexible and in our case firms should have incentives to overreport them. Raw materials, electricity, fuels, and services are what researchers have in mind when they refer to intermediates. In the context of tax evasion in Colombia, materials are the input of interest for several reasons. 

| Study | Intermediates|
|:-----:|:-------------|
| Levinsohn and Petrin (2003) | Materials, Electricity, and Fuels |
| Gandhi, Navarro, & Rivers (2020) | Materials, Energy (Electricity and Fuels), and Services |

First, firms have incentives to overreport production expenses to evade CIT, but only VAT deductible intermediates reduce their VAT burden. In fact, Colombia used system of refunds to companies with VAT tax balances in their favor. Raw materials are VAT deductible during the whole period of out data, 1981-1991. In addition, materials are the greater share of the firm's expenses among the other intermediate inputs. 

Electricity was mainly provided by government companies during this period. Even though there were private participation in the market, the data shows that corporations sold most of the private electricity. In our paper, we argue that Corporations are the firms with the lowest incentives to misreport their commercial activity. Therefore, it could have been relatively riskier to fake an electric bill than other inputs. Why? Because any electricity bill not coming from a Corporation or a Government company might look suspicious. In addition, it is unclear that firms could deduct from their taxes their electric bill. Finally, electricity is a small share of the firm's expenses in the data.

Fuels consumed in production were deductible however these represent a non-significant share of the firms' expenses.

Finally, only repair and maintenance services were taxed from the beginning during this period. The authority gradually introduced services they could control easily like telephone and telecommunication, insurances, airline tickets, and parking, among others. The rest of the services look more like fixed costs and not like intermediate inputs for production, or at least they do not necessarily increase with production. Take for instance, telephone bills. They might increase if an increase of output comes from handling more clients, but they might keep the same and production might increase if current clients increase their volume of demanded products.

## Industries

Given that I'll focus on materials, the industries I pick would have to make sense. Meaning, that firms should have nontrivial incentives to overreport raw materials to evade taxes and raw materials should represent a nontrivial share of their total production expenses.

To start, unprocessed primary goods such as mining, agricultural, fishing, and forestry were exempt of sales taxes. If the main raw materials of an industry is a primary good, then firms in that industry would have no incentive to overreport their raw materials because they are not paying sales taxes on their raw material that could be credited towards the taxes they have to pay for their sales. Industries like concrete and clay used in construction (369-Non-Metallic Minerals) and leather products (323-Leather tanning and dyeing, Fur skins) might fall into this category.

For other industries, few specialized suppliers provide their main raw materials. These firms might have to import a non-trivial share of their materials. It would be highly suspicious to fake invoices for raw materials that come from few known local and international suppliers. For example, plastic pellets the main raw material in injection molding and plastic products (356) are supplied internationally by a handful of suppliers located in the US and Europe. 

Likewise, industries exempt of sales tax would have relative lower incentives to evade than non-exempt. In Colombia, firms producing foodstuffs (311 and 312), drugs, textbooks, transportation equipment (384), agricultural machinery (382-Non-Electrical Machinery including Farm Machinery), and equipment (383-Electrical Equipment) were exempt of sales taxes since 1974. Exemption to Agricultural machinery and transportation equipment was eliminated in 1984. Almost half-way through the data.

(In addition, exporters were exempted from sales taxes. )

Lastly, it would be better to avoid industries selling a significant share of their output directly to consumers and retailers. Tax evasion through underreporting of sales severely affected Colombia during this time [@Perry1990]. It has been documented elsewhere that revenue underreporting is most significant for firms selling directly consumers. Why? Firms might offer consumers a discount if they do not request an invoice. Since the consumer is the final payer of the sales tax, they are more like to cooperate. On the other hand, firms selling to other firms face counterincentives. The firm buying the product is interested in having an invoice to report the sales tax pay to reduce the balance of the sales tax they collect when selling. In addition, during this period there was a tendency to create fictitious distributors to reduce the tax base. 

A report based on a sample from that period in @Perry1990 reveals that industries 322 (Wearing Apparel — 67.5\%), 324 (Footwear — 49\%), 342 (Publishing — 53.9\%), 369 (Non-Metallic — 50\%), and 390 (Other Manufacturing — 61.3\%) sell half or more of their output to retailers and directly to consumers.


| SIC    | Total no. of firms | % to retailers | % to public | % retailers and public combined | % government | % wholesalers |
|--------|-------------------:|---------------:|------------:|--------------------------------:|-------------:|--------------:|
| 312    | 25                 | 24.16          | 15.72       | 39.88                           | 1.20         | 58.92         |
| 313    | 3                  | -              | 29.33       | 29.33                           | 0            | 70.67         |
| 321    | 8                  | 15.06          | 0.11        | 15.17                           | 1.17         | 83.67         |
| 322    | 2                  | 52.92          | 14.58       | 67.50                           | 0            | 32.50         |
| 324    | 5                  | 45.00          | 4.00        | 49.00                           | 0            | 51.00         |
| 332    | 8                  | 10.85          | 20.15       | 31.00                           | 5.92         | 63.08         |
| 341    | 6                  | 5.00           | 0           | 5.00                            | 0            | 95.00         |
| 342    | 9                  | 19.44          | 34.44       | 53.89                           | 7.22         | 38.89         |
| 351    | 5                  | 15.20          | 6.00        | 21.20                           | 2.80         | 76.00         |
| 352    | 8                  | 37.81          | 5.50        | 43.31                           | 4.47         | 52.22         |
| 353    | 3                  | 5.67           | 5.00        | 10.67                           | 0            | 89.33         |
| 355    | 5                  | 21.00          | 0           | 21.00                           | 0            | 79.00         |
| 362    | 1                  | 10.00          | 0           | 10.00                           | 0            | 90.00         |
| 369    | 8                  | 21.25          | 28.75       | 50.00                           | 12.88        | 37.13         |
| 372    | 3                  | 10.00          | 0           | 10.00                           | 1.67         | 88.33         |
| 381    | 22                 | 12.41          | 14.73       | 27.14                           | 2.50         | 70.36         |
| 382    | 20                 | 11.20          | 30.00       | 41.20                           | 9.00         | 49.80         |
| 383    | 15                 | 13.87          | 7.13        | 21.00                           | 9.07         | 69.93         |
| 384    | 7                  | 0              | 34.57       | 34.57                           | 0            | 65.43         |
| 390    | 3                  | 58.00          | 3.33        | 61.33                           | 3.33         | 35.33         |
| 356    | 11                 | 15.55          | 6.00        | 21.55                           | 3.18         | 75.27         |
: Distribution of Sales from Manufacturing Firms, by type of Purchaser (in percentage) [@Perry1990] {#tbl-1984-manu-sales}