\begin{anfxnote*}{intro background}

Tax evasion and productivity in Mexico and Colombia

To lay out the context of the empirical approach and justify some assumptions during the estimation, this section provides a general overview of the corporate tax system in both Mexico and Colombia, and firm-level productivity estimates from previous work. The objective is to highlight the *relevance* of tax evasion in both countries and how it relates to the *critical* questions regarding productivity.


In Mexico, firms are subject to payroll taxes, value added taxes (VAT), and income taxes (ISR). Firms with annual revenues below 2 million pesos are taxed under the regime of small contributors (*Regime de Pequeños Contribuyentes—REPECO*) at 2 percent of revenues, while firms above that threshold are taxed at 30 percent. In 2013, 93.7% of all firms in manufacturing, commerce, and services could qualify for the REPECO[@Levy2018].

Some argue this discontinuity along other factors generate incentives for firms to stay small or declare profits below 2 million Mexican pesos (MXN).

\end{anfxnote*} 

# Tax evasion through input overreporting by false invoicing

Cost overreporting has been largely overlooked by the literature, however, recent empirical evidence shows that this form of tax evasion is widespread and quantitatively significant. Using transaction-level data from Ecuador, @Carrillo2022 expose that tax evasion through overreporting is not limited to small firms and that these transactions reach up to 14.1% of the value of the firm's total purchases. 

The evidence from Ecuador also demonstrates that firms overreport the intermediate inputs and that firms at the top of the size distribution do not evade taxes by input overreporting —this is relevant for our identification strategy. Firms overreport most strongly intermediate —non-labor non-capital— inputs: domestic purchases, other production costs, and imports. Top-sized firms have stronger incentives to avoid illegal behavior or they can use more sophisticated and profitable avenues of tax avoidance that do not require evasion using fake invoices [@Bustos2022].

Cost overreporting is not unique to Ecuador. According to a report from the OECD (2017), fake invoicing is internationally pervasive. There is evidence of overreporting from Latin America, Europe, Asia, and Africa[^int]. 

[^int]: In Latin America, Mexico lost around 3 billion EUR in tax revenue between 2007 and 2009 because of fake-invoice deductions. According to the country's tax authority (SAT), between 2014 and 2018, annual tax revenue lost due to ghost firms was about 5 billion MXN, 0.03% of the country's average GDP during the same period. For Colombia, the estimated tax revenue lost due to ghost transactions in 2019 was about 2,300 billion COP, 0.2% of the country's GDP [Portafolio, 2019 in @Carrillo2022]. For Chile, tax evasion by false invoices in 2004 amounted to 328 billion CLP, 0.2% of the Chilean GDP. In Europe, fake-invoice tax evasion in Poland amounted to 103,850 million PLN, 5.6% of Poland's GDP in 2016 (Poland's Minister of Finance, 2018). There is also some evidence in Asia, for South Korea (Krever, 2014) and China (Hashimzada et al., 2010; Barboza, 2013), and in Africa, for Kenya (Kenya Revenue Authority; Mak'Osewe, 2019), Rwanda (Mascagni et al., 2019; 2021), and from the African Tax Administration Forum (Brain and Nwankwo, 2018).

## Colombia 1981-1991

During this period, Colombia went through three fiscal reforms (1983, 1986, 1990). The 1983 reform tried to increase the country's income tax and reactivate the economy. The 1986 reform attempted to reduce evasion, among other things. The 1990 reform took place during the process of commercial opening. It had the objective of developing the capital market and incentivizing the repatriation of foreign capital.

### 1983 Reform

**Corporate profit tax (impuesto de la renta):** In 1983, Colombia reduced the maximum corporate tax rate from 56% to 49%. The progressive tax schedule went from 11.5% to 49%. However, the base of the taxpayers was increased.

**VAT (IVA)**: Increased from 6% to 10%. The 1983 reform set the VAT on national vehicles between 25-30%, depending on the motor. The motorcycles' VAT rate was set at 20%.

The tax authorities focused on the 5% of the big taxpayers that constituted 80% of the country's tax revenue.

### 1986 Reform

**Corporate profit tax**: In 1986, Colombia set the corporate max tax rate at 30% starting in 1989. To ease the transition, they set tax rates of 33%, 32%, and 31% for 1986, 1987, and 1988.

The reform relocated the tax collection and reception of tax reports to the banking system. Likewise, the 1986 reform increased the control over the big taxpayers.

### 1990 Reform

Corporate income tax: among other things, the foreign investment tax rates were reduced. Also, the reform reduced the base of the taxpayers obligated to file tax reports.

VAT was increased from 10% to 12%. In addition, several exceptions were eliminated, so the basket of taxed goods increased.

Import taxes were reduced and some goods were exempted.


\begin{anfxnote*}{prod}

Productivity

Productivity has stagnated in Mexico during the last decades despite macroeconomic stability and significant growth in human capital [@Levy2018]. Are the firm-level productivity measures reliable considering the potentially high tax evasion by firms?

In the context of my approach, the previous paper provides quantitative evidence for:

- Monotonic relation between size and tax evasion
  - The probability of engaging in cost overreporting through ghost firms increases monotonically in firm revenue.
- Firms at the top of the size distribution don't overreport inputs
  - Share of ghost deductions increases throughout much of the size distribution, *except at the very top* —very large corporations might have stronger incentives to avoid illegal behavior or they can use more sophisticated avenues of tax avoidance that do not require evasion using fake receipts (Bustos et al., 2022)
- Timing of the evasion decision
  - Ghost transactions are clustered towards the end of the tax year
  - Consistent with firms assessing their annual revenues at the end of the year and then utilizing ghost transactions to achieve a target reported profit level or rate for tax purposes
- No economic activity behind overreporting
  - Ghost transactions bunch at round numbers
  - Ghost transactions bunch below the financial system payment threshold
- Cost overreporting mainly on non-labor costs (intermediates)
  - Adjusting firms reduced most strongly non-labor costs: domestic purchases, other production costs, and imports
- No underreporting in firm-to-firm sales
  - There was no offsetting behavior as in revenue misreporting studies
- Conditional on being identified as a ghost client, the overreporting level does affect your probability of being audited
  - Notified firms had 2.4 times higher median tax liability, the median amount of ghost deductions of these firms was $181,000 (mean $338,000) and the median share of ghost deductions out of their total purchases was 26% (mean 38%)


\end{anfxnote*}