## Lit Review Notes

For personal reference, to be removed from the final version.

### @Dabla2019

Productivity improvements by firms can causally lead to lower tax evasion, i.e., underreporting sales for tax purposes. In other words, an increase in firm productivity leads to a higher share of sales reported for tax purposes. The authors use the self-reported share of declared income as a proxy for tax evasion.

Limitations: Using the World Bank Enterprise (47 emerging and developing countries) survey question to get the percentage of sales that are reported for tax purposes, which is used to measure tax evasion. In addition, productivity is measured as the log of sales per worker. No access to quantities data, they use LP but with sales and workers.

Undisputed (?) facts: 1) Tax evasion is higher in poor countries; 2) Tax evading firms tend to be less productive (?).

Productivity gaps between firms that comply with taxes and regulations and those which do not are significant, (between 25 to 50 \%) (Amin et al. 2019; Fajnzylber, 2011; Busso et al., 2012). These large productivity gaps can translate into low-economy wide productivity and growth: 1) if, by not complying with existing taxes and regulations, firms enjoy a potentially large implicit subsidy that allows them to stay in business despite low productivity, or 2) to expand their market share at the expense of more productive firms (Farrell, 2004; Bobbio, 2016).

Almeida and Carneiro (2009): Tax evasion may also increase firms' efficiency (productivity?). Avoiding onerous taxes might confer firms more flexibility in their employment and production decisions.
 
Kleven et. al (2016): Larger firms are less likely to avoid taxes. firms’ use of business records increases as it hires more employees. They show that the government may be able to enforce higher tax compliance even in the presence of a low threat of audit due to the increased ease of whistle-blowing as the firm grows.
 
tax evasion is hidden so that it is difficult to obtain precise measures (Kundt et al., 2017; Slemrod and Weber, 2012)

Loayza and Rigolini (2006) and La Porta and Shleifer (2014): informality is larger in lower GDPpC countries
 
Tax evasion and informality are associated with lower income levels and productivity (Dabla-Norris and Feltenstein, 2003; Loayza, 1996; Sarte, 2000)

### @Paulus2015

The author models discrepancies between tax records and income survey data as individual tax evasion and measurement error jointly. Using data for Estonia, the author finds that people in the bottom and the top part of earnings distribution evade much more and about 12% of wages and salaries in total are underreported. The identifying assumption, i.e., location condition, is that people working in the public sector cannot evade taxes. In other words, measurement error is unrelated to the sector where the individual works while the same does not hold for tax compliance.

The main constraint for empirical research on tax evasion is the lack of suitable data. This is worse for developing countries. A measure of undeclared income for individuals is needed. This kind of data is usually unreliable and very difficult/or expensive to obtain.

Baldini et al. (2009) use linked income data with tax records at the individual level to estimate tax evasion. However, the author assumes people report their true income in the survey to obtain a measure of non-reporting. Furthermore, in the measurement error literature, several studies assume the opposite, e.g. Krueger (1991) and Bollinger(1998); survey of lit Chen et al. (2011) and Bound et al. (2001). Linked data is referred to as Validation data in the measurement error literature. Later studies have started to consider matching errors (Kapteyn and Ypma, 2007; Meijer et al., 2012) and errors in register data (Abowd and Stinson, 2013).

Pissarides and Weber (1989) pioneered a methodology to study underreported income. They assume that the underreported income for one population group is inferred from a comparison with a reference group assumed to have negligible non-compliance but to be similar in other respects. These types of studies assume implicitly that the underreporting of income in a survey corresponds to the underreporting of income to the tax authority. 

### @Slemrod2019

Tax-evasion policies have been a greater priority in developed countries since the 2008 great recession (IMF, 2015). For example, the UK announced efforts to combat tax avoidance, tax evasion, and 'imbalances' in the tax system that would bring in \pounds 5 billion in additional revenue each year. 

Tax evasion matters because it affects both the resource cost of raising taxes and the distribution of the tax burden, i.e. core interests of public economics. Policy question? Does curbing evasion improve the equity and efficiency of the public finances, given the cost of doing so? If so, what's the best way to go about it? 

Tax evasion creates horizontal inequity because people evade taxes by different proportionate amounts because of differences in personal characteristics —risk aversion, tax system, and honesty— and because of different opportunities and potential rewards for evasion. Likewise, efforts to combat tax evasion might create vertical inequity. For example, going after lower-income households such as the IRS fighting fraud related to the earned income tax credit (EITC) than going after unreported foreign accounts that are more likely to be held by high-income households.

Tax evasion creates efficiency costs, e.g., individual's cost of implementing and hiding non-compliance, tax authority's cost of combating non-compliance, etc. Tax evasion also creates socially inefficient incentives to engage in activities that facilitate tax evasion. For example, tax-noncompliance opportunities attract people to self-employment who would otherwise be employees.

Tax evasion creates misallocations. For example, it can cause companies that otherwise would not find it attractive to do so to set up operations in a tax haven to facilitate or camouflage evasion.

Curtailing tax evasion cost shapes optimal policy —it is not optimal to completely eradicate tax evasion because of the cost of doing so. The presence of evasion also alters the optimal setting of tax rates —because it affects the marginal efficiency cost of so doing— and the choice of the tax base —because different tax bases are more or less susceptible to evasion. 

Slemrod and Weber (2012) review macroeconomic measures of the informal economy.

The standard tax evasion framework is the model of tax deterrence by Allingham and Sandmo (1972), who adapted Becker's (1968) model of criminal behavior to tax evasion. A relatively recent simplified framework is where the maximand is $y(1-t)+te-c(e,\alpha)$, $y$ is income, $e$ is the understated tax liability, $t$ is a linear tax rate, and $c$ is the private cost of evasion which includes the utility cost of bearing risk and the expected value of punishment. The private cost may depend on the amount of attempted evasion and $\alpha$, the vector of enforcement instruments, such as the extent of auditing.

The model predicts that a risk-averse agent will evade taxes if the expected return is positive. Additionally, an increase in either the probability of detection or the penalty if detected will reduce evasion. Importantly, the effect of the tax rate is less clear, for even its sign depends on the penalty function (Yitzhaki, 1974). 

What matters about $p$ is the perception of taxpayers. Much work is focused on what alters the taxpayer's perception of the enforcement environment.

This framework naturally applies to individuals, and small, single-owned firms. Large firms might be risk-neutral rather than risk-averse.

The challenge of measuring tax evasion is the incentive of evaders to conceal their behavior. Many taxpayers are unwilling to respond accurately maybe because of the threat of punishment or social shame. For this reason, even the most credible empirical studies of evasion don't actually have a reliable measure of evasion.

Tax gap studies by auditing (real differences between countries' tax gaps or differences in methodologies?): 
\begin{itemize}
\item U.S. Overall gross tax-gap average over 2008-10 was \$458 billion USD, 18.3\% of estimated tax liability (IRS, 2016). IRS National Research Program (NRP). 
\item UK: overall tax gap from 2013-2014 6.4\% of true liability: 6.4\% for the corporation income tax 5.0\% individual income tax, and 11.1\% value-added tax (VAT). Small- and medium-sized enterprises account for over half of the overall tax gap (HMRC, 2015). Her Majesty's Revenue and Customs (HMRC, 2015) Toro et a. (2013). 
\item Denmark overall tax gap is only 2.2 percent of net income (Kleven et al., 2011).
\item OECD(2015) other countries.
\end{itemize}

Sharp variations in the compliance rate by the extent of information reporting to the tax authority provide compelling evidence that the probability of successful evasion play a key role in the deterrence of tax evasion. For example, in the US, the estimated non-compliance rate when there is little to no third-party-reported information (e.g., self-employment income) is 63\%, compared to 19\% and 7\% for 'some' and 'substantial' information reporting, respectively. Small businesses represent a large portion of the tax gap in individual income with approximately 47\% of underreporting. In contrast, only 1 % of non-compliance is estimated for employee wages and salaries —substantial information reporting. Kleven et al. (2011) find a similar disparity, but lower, non-compliance rates in Denmark, where 14.9 \% for self-employment income but less than 1\% for third-party reported items. In other words, when the information reporting renders the likelihood of evading taxes successfully near zero, evasion is eradicated; when the likelihood is higher, evasion proliferates.

Administrative data: Canada, UK, Brazil, Chile, China, Costa Rica, Ecuador, India, Pakistan, Rwanda, Tunisia, and Uganda. US access https://www.irs.gov/pub/irs-soi/16jsrpprojects.pdf

RCT's review: Hallsworth (2014)

Bérgolo et al. (2018) RCT with firms using letters. Value-added-tax compliance, 20,000 Uruguayan small and medium-sized firms. The authors find that adding to the baseline letter a paragraph with statistics about the probability of being audited and the penalty rates increased tax compliance by about 6.3 percent (about one-fourth of its current level), and adding a paragraph that informs firms that evading taxes increased the probability of being audited increased tax compliance by about 7.4 percent.

Ortega and Scartascini (2018) Colombia, individuals. Method of communication. The authors find sizable differences across delivery methods. Personal visits by a tax inspector are more effective than the impersonal methods; they are, alas, also much more expensive. In a follow-up study, Ortega and Scartascini (2015) find that the effect of phone calls falls between those of the impersonal methods and the personal visits.

Almunia and Lopez-Rodriguez (2018) study the behavior of Spanish firms in response to a notch in enforcement intensity that arises because the Spanish Large Taxpayer’s Unit (LTU) monitors firms with revenues above €6 million for all major taxes. Sure enough, there is significant bunching of firms just below the threshold. The bunching is more pronounced for firms that produce intermediate goods, which makes sense because their transactions create more of a paper trail than firms that sell to final consumers, and thus the discontinuous increase in enforcement intensity affects these firms more than retailers.

Examining data from Ecuador, Carrillo, Emran, and Rivadeneira (2012) find evidence of bunching in reported tax liability just above the withholding threshold, suggesting that some firms manipulate their self-reported tax liability and possibly real economic choices to minimize expected tax payments subject to the discontinuity in the audit probability. Third-party data on sales and intermediate input costs reported by large firms who act as withholding agents indicate that bunching is indeed associated with tax evasion: self-reported sales are smaller than third-party reports for more than 10 percent of firms. "withholding”, large firms withhold and remit to the tax authority a fixed share of their purchases from small firms (and individuals), who can then apply the withheld amount as a credit against their self-reported tax liability. While withholding does not change the firms’ true tax liability, there is typically a discontinuity in the audit probability at the withholding rate; firms seeking tax refunds (because self-reported tax liability is lower than the withheld amount) are audited at a higher rate than firms making additional tax remittances.

In Chile, firms can only claim tax credits for inputs bought from tax-compliant suppliers, the invoice–credit VAT system has a built-in (albeit imperfect) self-enforcement mechanism for firm-to-firm transactions. Pomeranz (2015) tests this hypothesis by mailing increased-audit-threat letters to over 100,000 randomly selected Chilean firms, using a sample of over 300,000 firms receiving no letter as the control group. Consistent with theoretical predictions on the self-enforcement mechanism, the increase in VAT receipts (and therefore the inferred level of evasion) induced by the letters is concentrated at the level of sales from firms to final consumers, for which there is no paper trail.

In Ecuador, Carrillo, Pomeranz, and Singhal (2017) examine the effect of a change in the tax authority’s use of third-party information on reported corporate tax revenues. In the authors' study, the Ecuadorian tax authority informed some firms of the discrepancy between the two reports and offered them the opportunity to file an amended return. The authors compare the reporting behavior of firms before and after the notification and find that 24 percent of firms underreported revenue in the years when the government did not use the third-party-verified information. In the three rounds of the experiment, 11–19 percent of notified firms filed an amended return. 

In amended returns, firms correctly reported their revenues but also increased their reported costs almost one-for-one with the increase in reported revenues (96 cents for each dollar!), nearly eliminating any impact on apparent tax liability. This study also reveals that reported costs were lower than third-party information on costs, which at first blush seems to be at odds with a model of firms that seek to maximize after-tax profits. The authors propose that this behavior is consistent with firms who may believe that the probability of an audit is a function of firm size and profits. To appear small, and lower the odds of being audited, some firms may underreport both revenues and costs.

Kumler, Verhoogen, and Frías (2013) study the effects on evasion of a 1997 pension reform in Mexico that tied younger workers’ retirement benefits more closely to the wage reported by employers. This reform provided a new incentive for this group of workers to ensure that their employers accurately reported their wages, which in turn might lower payroll tax evasion by firms. To examine the impact of this initiative, the authors combine two sources of data on wages: administrative data from the Mexican Social Security Insitute (IMSS) and household survey data from the Encuesta Nacional de Empleo Urbano (ENEU). The authors find that, consistent with a decline in evasion, the gap in median or mean wage within a cell between the ENEU data and the IMSS data fell for younger age groups after the pension reform but, as predicted, for older workers not affected by this reform there was no decrease in the gap between the two income reports.

In Pakistan, corporations either pay a tax on profits or turnover, depending on which liability is greater. This effectively implies that at a profit rate lower than the ratio of the turnover tax rate to the profit tax rate, firms cannot deduct costs. Because in Pakistan a large portion of evasion is through misreporting of costs, this tax regime trades off loss in production efficiency (as firms move from a neutral profit tax to a distorting output tax regime) for a gain in revenue collection. Best et al. (2015) use administrative data on the universe of corporations in Pakistan to estimate the elasticity of taxable income using the bunch-ing of firms below the threshold profit rate. They find clear evidence of such bunching, whose location shifts along with changes in tax rates that move the threshold. Using the analysis-of-bunching methodology, they estimate that turnover taxes reduce evasion by between 60–70 percent. 

Relevance of tax evasion
Widespreadness of tax evasion
Seminal model of tax evasion
Real effects of tax evasion
firm-to-firm sales less likely to evade taxes
small firms more likely to evade taxes
evidence of misreporting of costs (Pakistan)
Chile and Colombia tax evasion evidence

### @Carrillo2022

The authors study tax evasion through the use of ghost firms — fake firms that issue fraudulent receipts so that their clients can claim false deductions. Using transaction-level data from Ecuador, the research documents that ghost transactions are widespread; prevalent among large firms —(!) measured as revenue level[ [related to size]— and firms with high-income owners —owners with experience in tax evasion? sophisticated or less risk-averse owners?—; and exhibit suspicious patterns: bunching at the end of the fiscal year [tax evasion decision is realized post realization of productivity and true input optimization], at round numbers, and just below financial system thresholds [no real economic activity behind].

Globally widespread but extremely limited researched problem. "Ghost firms" —also known as "invoice mills", or "missing traders"— issue fraudulent receipts that allow the receivers to claim additional tax deductions on value-added (VAT) and corporate income taxes (OECD, 2017; Keen and Smith, 2006) Appendix B.

Data: firm-to-firm transaction-level data with 800 'ghost firms' and firm owners of Ecuatorian firms data.

Widespread and quantitatively important, not limited to small, semi-formal firms, benefits those at the top of the income distribution. In 2015, 4.7\% of potential clients took deductions from a ghost firm. Annual ghost deductions were 14.1% of the value of their purchase deductions [huge number!]. Larger firms are more likely to engage in ghost transactions and feature larger shares of ghost transactions in total input costs [a function of size]. Ghost deductions are disproportionately used by firms owned by high-income individuals.

Process: Given a list of identified ghost firms (2016) by the Ecuadorian Internal Revenue Service (SRI), the authors identified ghosts' clients —firms with at least one purchase from ghosts firms— with administrative data -which includes annual corporate and individual income tax filings in Ecuador (2010-2017) and monthly purchase annexes (2010-2015). The sample is restricted to firms that are required to file purchase annexes: incorporated firms (88\%) and large sole proprietorships (12\%) (i.e., annual sales > \$100,000, annual costs > \$80,000, or capital above \$60,000)

1. Tax deductions based on fake receipts from ghost firms are widespread and large. 10.4\% of unique firms filed deductions based on receipts from at least one identified ghost firm. On average, 3.6\% of all purchases of ghost clients are from ghosts, amounting to 10.4% of the value of their purchase deductions. These shares are the highest,4.6\% and 14.1\%, for 2015, the year before the ghost list was collected. Earlier ghosts might have disappeared by the time the list was established. Total tax evasion was \$2.1 billion in value, 1.7\% of tax evaded for corporations and 11.5\% for sole proprietorships.
2. Evasion through ghost firms is more prevalent among relatively large firms. Ghost clients have higher revenues, costs, and tax liabilities. The probability of engaging in cost overreporting through ghost firms increases monotonically in firm revenue —maybe only because of more transactions. Share of ghost deductions also increases throughout much of the size distribution, except at the very top —very large corporations might have stronger incentives to avoid illegal behavior or they can use more sophisticated avenues of tax avoidance that do not require evasion using fake receipts (Bustos et al., 2022)
3. Ghost deductions are most prevalent in firms owned by high-income individuals. The probability of having ownership of a ghost client and the amount of ghost purchases attributed to individuals increases with individuals' income. The amount of additional tax as a share of owners' income is over 56 times higher in the top 5\% than in the bottom 80\% of the income distribution, and almost 170 times higher in the top 1\%. Ghost-firm-enabled tax evasion tends to reduce disproportionately the effective taxation of firms owned by rich individuals.
4. The number and value of ghost transactions are clustered towards the end of the tax year —the same as the calendar year in Ecuador. In December, there as twice as many ghost transactions as during the six previous months of the year. Non-ghost transactions are only 6% higher in December. This is consistent with firms assessing their annual revenues at the end of the year and then utilizing ghost transactions to achieve a target reported profit level or rate for tax purposes. Similar to US firms spending more on capital investment towards the end of the fiscal year to reduce tax obligations (Xu and Zwick, 2022).
5. Ghost transactions bunch at round numbers more prevalently than non-ghost transactions. This is consistent with ghost transactions representing false activity (Klimek et al, 2018; Nigrim, 2018).
6. Ghost transactions exhibit bunching below the financial system payment threshold. In Ecuador, transactions above \$5,000 (gross-of-VAT) are required by law to be made through the formal financial sector (e.g. electronic transfers, checks, or credit cards). Ghost transactions bunch just below \$5,000. In contrast the distribution of non-ghost transactions is smooth through the \$5,000 threshold.

Lit on tax evasion via ghost firms is extremely sparse. Waseem (2020) Pakistan. Policy: VAT rates reduced to zero. Ghost firms decreased. Most ghost deductions are claimed by exporters. Ghost deductions are a large share of over-claimed refunds for exporters. Mittal et al. (2018) develop a Machine Learning algorithm to detect ghost firms.

Most recent work on tax evasion focuses on firms' revenue misreporting (Slemrod, 2019; Pomeranz and Vila-Belda, 2019), but few have studied firms' cost misreporting. Recent firms' revenue misreporting studies have found that enforcement policies targeting revenue underreporting led to increasing reported costs —to offset tax liabilities—, but there is no offsetting behavior —reduction in reported revenue— in the study by Carrillo et al. (2022). This is consistent with third-party information reporting —firm-to-firm transaction level data is used in this study— decreasing the incentive to evade by increasing the probability of getting caught.

Other studies finding bunching at the thresholds are:
- VAT reporting thresholds: Onji, 2009; Asatryan and Peichl, 2017; Luksic and Mittal, 2019; Liu et al., 2021.
- Different tax regimes and regulations: Hasegawa et al., 2013; Best et al., 2015; Almunia and Lopez-Rodriguez, 2018; Lopez-Luzuriaga, 2019;  Chen et al., 2021; Clifford and Mavrokonstantis, 2021; Overview: Kleven, 2016.

Intervention: Tax authority challenged deductions from firms with ghost transactions (ghost clients) during 2010-2015 by notifying them via email.
 
[What goes into the cost overreporting function? Tax authority chooses effort (b(type)-c(type))e (?)]Tax authorities target firms with higher potential tax recovery. In this study, notified firms were larger than typical incorporated ghost clients —authors only had access to the data on incorporated firms that were notified. Notified firms had 2.4 times higher median tax liability, the median amount of ghost deductions of these firms was \$181,000 (mean \$338,000) and the median share of ghost deductions out of their total purchases was 26\% (mean 38\%). [conditional on being large, the overreporting level does affect your probability of being audited.]

[Evidence of overreporting in intermediates] Adjusting firms reduced most strongly non-labor costs: domestic purchases, other production costs, and imports. Some offsetting behavior was observed; Firms increased labor, inventory, and financial costs. However, overall total costs still decreased on average by 72 cents for every dollar contested in the notification.

Many firms did not respond to the notifications. A portion might be explained by failure in communication (e.g., letters not reaching the firm or the right person within the firm). Firms might choose not to amend knowing the tax authority has limited capacity for follow-up enforcement. Adjusting firms tend to be somewhat smaller than all the notified firms.

The intervention resulted in large reductions in firms' reported costs. The reduction in costs increased tax liabilities by \$20.6 million, 81\% increase on the \$25.4 million originally filed by adjusting firms. On average, reported costs were reduced by \$229,000

Firm-to-firm transactions —third-party reporting: firm's sales to other firms can be cross-checked— are less like to underreport revenue. Firms did not adjust revenues down to offset tax liability resulting from the decrease in costs —as in other studies where the enforcement strategies pushing firms to truthfully report their revenues led firms to make large offsetting adjustments by increasing reported costs (Asatryan and Peichl, 2017; Carrillo et al., 2017; Slemrod et al.,2017; Almunia and Lopez-Rodriguez, 2018; Mascagni et al., 2018; Naritomi, 2019; Li andWang, 2020)

No evidence that the intervention was followed by firms going out of business or de-formalizing; consistent with ghost clients being large and established. 

International prevalence of false invoicing (ghost firms)
- Mexico: between 2014 and 2018, the estimated annual tax revenue lost due to ghost firms was 5 billion MXN (SAT), 0.03\% of Mexico's GDP; 8,500 identified ghost firms in 2018 (Senado de la Republica, 2019).
- Chile: historically, false invoices represent between 15\% and 25\% of total VAT evasion. In 2004, fake-invoice tax evasion was 114 billion CLP, 0.2\% of Chile's GDP (Gonzalez and Velasquez, 2013; Jorrat, 2001; CIAT, 2008). 
- Colombia: fake-invoice tax evasion was around 2,300 billion COP, 0.2\% of Colombia's GDP (Portafolio, 2019).
- Poland: In 2016, fake-invoice tax evasion amounted to 103,850 million PLN, 5.6\% of Poland's GDP (Poland's Minister of Finance, 2018).
- Asia: South Korea (Krever, 2014) and China (Hashimzada et al., 2010; Barboza, 2013).
- Africa: Kenya (Kenya Revenue Authority; Mak'Osewe, 2019); Rwanda (Mascagni et al., 2019; 2021); African Tax Administration Forum (Brain and Nwankwo, 2018).

### @McLure1989

#### Colombian Tax System

The tax system of Colombia has been under constant study and revision since the 1960s.

During the early 1960s, a Fiscal Survey of Colombia (1965) led by Professor Milton Taylor was prepared as part of the ongoing program of the Organization of American States and the Inter-American Development Bank. This study led to important administrative innovations, but few concrete substantive reforms.

In 1970, Professor Richard Bird prepared a report, influential in terms of policy, based on his experience as a resident advisor to the government of Colombia on tax and fiscal policy during the period of 1964-1966.

In 1968, Professor Richard Musgrave was commissioned by President Carlos Lleras Restrepo to appraise the tax system and make recommendations for reform with the help of Colombian and foreign experts. The resulting document, Fiscal Reform for Colombia: Final Report and Staff Papers of the Colombian Commission on Tax Reform, significantly shaped the 1974 and subsequent tax reforms. This report has also become a classic in the field of tax reform in developing countries.

In late 1974 Colombia undertook a major fiscal reform drawing heavily on the recommendations of the Musgrave Commission. 

Other influential documents during this period were La Reforma Tributaria 1974 (Gillis and McLure, 1974) and a World Bank report (McLure, 1982). Finally, there exists a report on the taxation of income from business and capital (McLure, Mutti, Thuronyi, and Zodrow, 1989?)

#### Income tax

At the time of the Taylor Mission, Colombia's system of *income and complementary taxes* consisted of a basic income tax, a net wealth tax, and an excess profit tax.

In the early 1960s, the base of the Colombian income tax was quite broad. It included all "enrichment"; it included corporate dividends and shares in the earnings of limited liability companies and partnerships.

During this period, high-income individuals could evade the individual income tax on dividends and interest on bearer securities, since a withholding tax of only 12 percent was levied on such income.

The income of individuals was taxed under a graduated schedule consisting of 56 rates, ranging from 0.50 to 51 percent. There was a complex system of personal deductions for expenditures on medical, educational, and other professional services; these deductions depended on the income and number of children of the taxpayer.

Tax incentives were provided for, among others, industrial enterprises. In addition, income tax exemptions, limitations, or reductions were granted to oil companies, certain mining companies, large-scale agricultural improvements, cattle-raisers, Colombian airlines, certain basic industries, manufacturers using products from *Paz del Rio* steel plant, and exporters other than coffee, petroleum, bananas, hides and precious metals.

Juridical persons were subject to graduated rates. Corporate rates (on *Sociedades anonimas*), which applied to all foreign entities, were 12, 24, and 36 percent. The rates applied to limited liability companies (*Sociedades de Responsabilidad Limitada*), the business forms used for many of the most important Colombian business ventures, were only 4, 8, and 12 percent, and the income of partnerships was taxed at rates of 3 and 6 percent. Whereas the income of proprietorships was taxed only in the hands of the owner under the individual tax, the income of juridical persons was taxed directly to the firm. The entire net income of limited liability companies (like that of partnerships) was taxed to the partners, whether or not distributed; by comparison, only dividends were taxed to owners of corporate shares.

The tax system of Colombia suffered from many administrative problems in 1960. A serious problem involved the interplay of an overly short statute of limitations (two years), a system of penalties and interest that encouraged false and delinquent returns, and an overburdened tax administration. In extreme cases, taxpayers could avoid taxation completely by deliberating reporting false information, and waiting for the statute of limitations to preclude correction by the fiscal authorities.

#### Net wealth tax

Since 1953, Colombia has imposed a tax on net wealth (*impuesto complementario de patrimonio*), apparently to increase the tax burden related to income from capital and to induce a more productive use of land. Taxable wealth was that held in Colombia, net of indebtedness. There were numerous exceptions, which paralleled, for the most part, those under the income tax. For example, there were exemptions for livestock kept for breeding purposes, certain agricultural investments, assets of Colombian airlines, investments in motor vehicle assembly or manufacturing plants, investments in securities of the *Paz del Rio* steel plant, and investments in certain basic industries and certain iron and steel fabricators.

#### Excess-Profits Tax

Colombia imposed an excess-profits tax beginning in 1935; this tax was repealed in 1974.

#### The Taylor Mission Proposals

The Taylor Mission produced an impressive analysis of the distortions and inequities that flow from the disparate treatment of individuals, corporations, limited liability companies, and partnerships. It noted particularly the case for integration of the corporate and individual income taxes. However, it concluded that such a policy, integrating corporate and individual income taxes, was not warranted at the time. McLure rationalizes this contradiction with political realism because the double taxation had been recently introduced in 1953. The Mission's recommendation focused on the interplay between the corporate income tax, two of the supplementary taxes on income, and the excess-profits tax. The Mission favored a tax increase in limited liability companies, which it acknowledges were used as "tax avoidance device". 

The Mission devoted particular attention to the agricultural sector because of the potential revenue being lost and the potential role of tax policy to stimulate efficient use of rural resources. The Mission proposed a presumptive calculation of income from agriculture equal to 10 percent of the assessed value of agricultural property.

The Taylor Mission also proposed administrative changes such as withholding for wages, salaries, interests, and dividends, the requirement of advance tax payments based on estimated liabilities, self-assessment, extension of the statute of limitations, and rigorous application of penalties.

#### Musgrave Commission's Proposals

For the most part, the Taylor and Musgrave recommendations for income tax reform were broadly consistent.

The Musgrave Commission repeated the call for heavier penalties for tax evasion. The Commission also suggested strategies to improve taxation of the *hard-to-tax* group such as small traders, independent professionals, and agriculture.

In contrast to the Taylor Mission, the integration of the taxes on business and on individuals was rejected by the Musgrave Commission. Instead, the Commission proposed that the income of corporations and limited-liability companies be subject to a unified system of taxation. The proposed system would consist of taxation at the entity level and at the individual shareholder level only on income that is distributed. Partnerships would be taxed at the entity level at a substantial lower rate, and subject to certain conditions limited-liability companies would be given the option to being taxed like partnerships; the partners' share in partnership profits would also be subject to individual taxation, whether distributed or not. 

#### Sales tax and VAT

Colombia introduced a national sales tax in 1965. This was a single-stage manufacturers' tax levied at rates of 3 to 10 percent on finished domestic goods and imports. Buyers' certification that goods would undergo further processing prevented the transaction from being taxed to avoid double taxation. This system led inevitably to double taxation and evasion. In 1966, this sales tax was converted into a crude credit-type value added tax (VAT), but one that extended only through the manufacturing level and allowed no credit for tax paid on capital goods.

#### 1974 reforms

The 1974 reforms were greatly influenced by the Musgrave recommendations, which were considered and refined by local experts during the intervening half-decade. These reforms rationalized many aspects of the income and net wealth taxes, and eliminated the tax on excess profits, added a calculation of presumptive income based on net wealth, and further improved the system of internal indirect taxes.

*Income*. The 1974 reforms eliminated many exemptions and other forms of preferential treatment for non-labor income, including the exclusion of interest on public debt, exemptions for automobile producers and private electrical companies, and deductions for reserves for investment. Exemptions remained intact for the airlines, publishing, and reforestation sectors, and for various activities in selected regions (primarily "frontier" and other less developed ones).

The 1974 reforms replaced graduated rates with flat-rate taxes for business income. But the taxation of corporations and limited liability companies was not unified. Instead, the income of corporations was taxed at 40 percent and that of limited liability companies and partnerships at a rate of 20 percent. As before, shareholders of corporations paid tax only on dividends, whereas owners of limited liability companies and partnerships were required to pay tax currently on the share of the profits of the company imputed to them.

The 1974 reforms extended the concept of presumptive income from only to the agricultural sector (1973) to the economy as a whole. Income was presumed to be no less than 8 percent of net wealth, defined generally in the same way as for the net wealth tax.

*Internal indirect tax*. The 1974 reforms eliminated the possibility of buying otherwise taxed items on an exempt basis simply by certifying to the seller that they were to be processed further; under the new law, the tax credit (invoice) system was extended to all such transactions. This created administrative headaches because of the many claims for refunds that had to be processed.

The law expanded the base of the VAT to reduce the regressivity of the tax at the upper en of the income scale. The VAT was applied to many services, including parking lots, insurance, international air fares, photographic developing and photocopying, telegraphic and telephone services, and fees of social clubs. Likewise, the degree of progressivity of the rate schedule applied to various goods, ranging from "wage" goods (6%) to luxuries (35%) was increased. The 1974 reforms also provided more widespread exemptions, for example, for almost all food and for selected agricultural machinery.

As under previous law, no credit was allowed on capital goods, in part to compensate for underpricing of capital resulting from various non-tax policies, including an undervalued exchange rate. On the other hand, the law contained anomalous provision that exempted imports of capital goods destined for "basic" industries. The combination of these policies placed domestic producers of capital goods at a competitive disadvantage relative to foreign producers of imported capital goods.

#### 1974-1986 Period

During this period of continued tinkering with the tax system in Colombia, some changes represented improvements, but the more important ones represented retrogression. These *counter-reforms* were in large a response to the pleadings of politically powerful economic groups.

For example, law 20 of 1979 effectively exempted cattle raising from income tax and arbitrarily reduced the value of breeding stock and dairy cattle for net wealth and presumptive income tax purposes by 50%.

Law 9 of 1983 a tax credit of 10% of dividends received was provided as a means of reducing double taxation of dividends. 

In addition, Law 9 of 1983 instituted a measure of presumptive income equal to 2 percent of gross receipts to supplement the measure based on net wealth. This reform was aimed specifically at the commerce and service sectors; the former were thought to evade the wealth-based presumptive tax by systematically understating inventories. In addition, it extended the presumptive income tax to limited liability companies.

Tax returns were not required if 80 percent of income was from labor subject to withholding, if the taxpayer was not an owner of shares in a limited liability company (ownership of corporate shares was allowed), and if the taxpayer was not liable for sales tax, among other requirements.

In 1983, the value-added tax (VAT) was extended to the retail level, with a *simplified system* being made available to small retailers in the effort to ease compliance costs and administrative burden. Services like hotels, computing services, maintenance, and rental of goods and fixtures were brought into the scope of the tax. Moreover, there was some unification of rates to alleviate the difficulties of dealing with differential rates at the retail level which led to an increase in the rate of (noncreditable) tax applied to domestically produced capital goods. Imported capital goods continued to be exempt from tax. In 1984, exemptions for agricultural machinery, transportation equipment, and certain other goods were eliminated.

#### The 1986 reforms

The 1986 reform reduced tax rates dramatically. The top tax rate applied to individual income was reduced from 49 to 30%; the same rate applied to the income of corporations and limited liability companies.

Expense deductions of independent professionals were limited to 50% of income in an effort to curtail a major source of abuse.

The 1986 reforms unified the taxation of corporations and limited liability companies by taxing both at a rate of 30%. It integrated the taxation of companies and individuals by exempting corporate dividends and participation in profits of limited liability companies from tax at the individual shareholder/owner level. Consistent with this treatment, losses, exempt income, and tax credits of companies cannot be used to offset income of their owners.

## @Perry1987

*Development of a Value Added Tax in Colombia*

