
## Related literature

\fxnote{Unfinished section}

### Tax evasion

A related strand of the literature is the traces of income, but those studies focus on tax evasion of individuals [@Pissarides1989; @Paulus2015]. In corporate tax evasion, the second observed measure, the output, depends on an additional unobservable, the productivity of the firm. In the traces of income literature, the objective is to recover the true income of potential tax evaders by comparing them with a group that is likely to not evade. For instance, in the seminar paper by @Pissarides1989, the authors argue that food consumption is a function of income but not of the kind of income, e.g., salary versus self-employment income. The authors conclude that the self-employed understate their income because they have a higher ratio of food purchases to reported income than salaried employees. 

### Production functions and productivity

In the production function estimation, two recent papers, Ursenbach (2022) and @Collard2020, examine the effect of measurement error in capital inputs on the estimation of production functions. This paper differs from them in that tax evasion is not a measurement error but a systematic optimal choice for firms to maximize their after-tax profits. In particular, tax evasion is not mean zero and it could be correlated with productivity and other characteristics of the firm. In addition, the focus of this paper is the intermediate inputs. Intermediate inputs are considered flexible inputs, unlike labor and capital. This is important because the proxy variable literature leverages the first-order conditions of the flexible input to identify productivity. This allows me to study productivity bias due to misreporting.


### Econometrics of unobservables

Lastly, this paper is also related to the work on the econometrics of unobservables [@Hu2008; @Hu2022; @Schennach2021]. In a series of papers, these authors study the identification the following problem under different conditions: $Y=m(x^*)+\nu$ and $x=x^*+\varepsilon$ with $x^*$ unobserved. In the case of the production function estimation, there is an additional unobservable, the productivity.