## Tax Evasion and Resource Misallocation

A popular way to decompose total productivity introduced by Olley and Pakes (1996) is the following :

$$
\varphi_t = \bar\varphi_t + \sum_{i=1}^I \left(s_{it}-\bar s_{t}\right)\left(\varphi_{it}-\bar\varphi_t\right)
$$

where $\varphi_{it}=\exp\{\omega_{it}+\varepsilon_{it}\}$ is the firm-level productivity, $s_{it}$ is firm' $i$ share of output at time $t$. $\bar\varphi_t$ and $\bar s_t$ represent the unweighted mean productivity and  unweighted mean share.

Intuitively, the more output is allocated to high productivity firms the higher the total productivity will be. Alternatively, the smaller the shares allocated to low productivity firms the greater the total productivity.

Ideally, we would like resources to be allocated to high productivity firms. Hence, the link between the decomposition of total aggregate productivity and missallocation.

In the tax evasion context, the productivity of misreporting firms would look lower than it really is. How would this affect our measures of total productivity? If misrrerporting firms have small shares, their corrected productivity measure might be closer to the mean reducing their contribution to total producvity, leading to lower measured levels of total producvity. 

In other words, tax evasion through cost overreporting might lead to biased measures of total aggregate productivity.

However, if we think about the marginal firm that is struggling to stay in the market, the additional income gained through misreporting might help her survive longer. Therefore, tax evasion increases misallocation in the sense that a share of the output is allocated to firms that otherwise would not be in the market. 

There are alternative ways to decompose total productivity that account for the entry and exit of firms (Foster et al. 2008). In addition, alternative measures to aggregate productivity have been used elsewhere (e.g. aggregate demand shocks in Eslava et al. 2004).

For example, we can decompose aggregate productivity like this

$$
\Delta\varphi_t = \sum_{i \in C}\bar s_i \Delta\varphi_{it} + \sum_{i\in C}(\bar\varphi_i-\bar\varphi)\Delta s_{it}+\sum_{i\in N} s_{it}\left(\varphi_{it}-\bar\varphi\right)-\sum_{i\in X}s_{it-1}\left(\varphi_{it-1}-\bar \varphi\right)
$$

where $\Delta$ is the change from $t-1$ to $t$, and the sets $C$,$N$, and $X$ represent the continuing, entering, and exiting firms.

In the case of corporate tax evasion a relevant measure could be aggregate profitability. Low productivity firms are surviving not because they are technologically efficient but because their profitatibility is marginally higher when they evade taxes. Decomposing an aggregate profitability measure by market shares and firm dynamics would indicate how exiting firms are contributing to the aggregate measure. Intuitively, again higher levels of aggregate profitability correspond to larger shares of the market being allocated to high profitability firms. 

In the absence of tax evasion, firms overreporting costs would have lower after-tax profits. The aggregate profitability level would be higher if these firms have small market shares and remain in the sample. On the other hand, the aggregate profitatibility level woud decrease if the small-share and low-profitability firms were to exit the market. 

Therefore, in the case of tax evasion, the key aspect of aggregate profitability is the counterfactual decision of low-profitability firms to exit the market in addition to the corrected profits if firms were not to overreport their costs.

Consequently, the economic model should account for firm entry and exit along with tax evasion.
