## Identification strategy

My identification assumption is motivated by the empirical evidence showing that very large firms do not evade taxes by input overreporting [@Carrillo2022]. Hence, I assume I know the quantile of the size distribution of compliant firms.


::: {.callout}
```{=tex}
\begin{ass}[Non-evaders]\label{ass-comp}
Firms above percentile $s$ do not overreport inputs $$\mathbb{E}[\varepsilon^M_{it}|S_{it}>s]=0$$
\end{ass}
```

:::

In addition, I impose the following timing assumption.

::: {.callout}
```{=tex}
\begin{ass}\label{ass-ind}
Firms choose overreporting $\varepsilon^M_{it}$ \emph{before} the output shock $\varepsilon^Y_{it}$
\end{ass}
```
:::

Assumption \ref{ass-ind} implies that input overreporting is independent of the current period output shock, $\varepsilon^M_{it} \perp \varepsilon^Y_{it}$. In the literature is not rare to assume that the output shock is not part of the information set of the firms, $\varepsilon^Y_{it}\not\in \mathcal{I}_t$ [@Gandhi2020]. Timing and information set assumptions are not uncommon for identification strategies in production functions and demand estimation [@Ackerberg2021; @Ackerberg2019].

### Identifying the production function parameters 

Suppose the production function is Cobb-Douglas, $G(M^*_{it}, K_{it}, L_{it})e^{\omega_{it}+\varepsilon^Y_{it}}=M^{*\beta}_{it}K_{it}^{\alpha_K}L_{it}^{\alpha_L}e^{\omega_{it}+\varepsilon^Y_{it}}$. Then, we can use the first-order conditions of the firms' cost minimization problem on the flexible input, as in @Gandhi2020, and assumption \ref{ass-comp} to recover the production function parameter $\beta$.

$$
\begin{aligned}
    \ln\left(\frac{\rho_t M^*_{it}}{P_{t}Y_{it}}\right)+\varepsilon^M_{it}&=\ln\beta + \ln \mathcal{E}- \varepsilon^Y_{it} \\
    \mathbb{E}\left[\ln\left(\frac{\rho_t M^*_{it}}{P_{t}Y_{it}}\right)\Bigg| S_{it}>s\right]&=\ln\beta
\end{aligned}
$$ {#eq-foc-cd}

$\mathcal{E}=\mathbb{E}[e^{\varepsilon_{it}^{Y}}|\mathcal{I}_{it}]$

Note that this is the case because $\mathbb{E}[\varepsilon^Y_{it}|S_{it}>s]=\mathbb{E}[\varepsilon^Y_{it}]=0$. That is, there is no selection on the output shock. Therefore, as long as our measure of size is not structurally related to  @eq-foc-cd --- like output or revenue in the same period---, the output elasticity of input, $\beta$, can be recovered.

### Identifying the Markov Process of Productivity

If we were to follow @Gandhi2020 to recover the Markov process of productivity, we could only have estimates for firms with size $S_{it}>s$. 

$$
\begin{aligned}
    \mathcal Y_{it}&\equiv \ln Y_{it}-\varepsilon^Y_{it}-\beta \ln M_{it}-\alpha_K \ln K_{it}-\alpha_L \ln L_{it}= \omega_{it}\\
    \mathbb{E}[\mathcal Y_{it}|\mathcal Y_{it-1},S_{it}>s] &= \mathbb{E}[\omega_{it}|\omega_{it-1},S_{it}>s] 
\end{aligned}
$$

However, it is likely that there would be selection on $S$, i.e., $\mathbb{E}[\omega_{it}|S_{it}>s]\not=\mathbb{E}[\omega_{it}]$. In other words, larger firms will have a higher probability of getting a higher draw of productivity. Therefore, the parameters of the AR(1) process of productivity would be biased.

However, for every firm, I can form the following variable using observed variables and the production function parameter I recovered from the first stage. 

$$
\begin{aligned}
    \mathcal V_{it}\equiv&\ln\left(\frac{\rho_t M_{it}}{P_{t}Y_{it}}\right)-\ln\beta \notag \\
    &=\ln\left(\frac{\rho_tM^*_{it}}{P_{t}Y_{it}}\right)-\ln\beta+\varepsilon^M_{it} \notag \\
    &=-\varepsilon^Y_{it} +\varepsilon^M_{it}
\end{aligned}
$$

This is useful because I can recover the tax evasion up to a random variable, $\varepsilon^Y_{it}$, with mean zero and, by assumption \ref{ass-ind}, independent of $\varepsilon^M_{it}$.

Likewise, I can recover the true inputs $M^*_{it}$ and productivity up to $\varepsilon^Y_{it}$.

$$
\begin{aligned}
    \mathcal M_{it}&\equiv \ln M_{it}-\mathcal V_{it}\\
    & = \ln M^*_{it} +\varepsilon^M_{it}-(\varepsilon^M_{it}- \varepsilon^Y_{it}) \\
    & = \ln M^*_{it} + \varepsilon^Y_{it} \\
    \\
    \mathcal W_{it} & \equiv \ln Y_{it} - \beta\mathcal M_{it}-\alpha_K \ln K_{it}-\alpha_L \ln L_{it}\\
    & = \beta\ln M^*_{it}+\alpha_K \ln K_{it}+\alpha_L \ln L_{it}+\omega_{it}+\varepsilon^Y_{it}-\beta\ln M^*_{it}-\beta\varepsilon^Y_{it}-\alpha_K \ln K_{it}-\alpha_L \ln L_{it} \\
    & = \omega_{it}+(1-\beta)\varepsilon^Y_{it}
\end{aligned}
$$

I can use $\mathcal W_{it}$ to recover $\delta=[\delta_0,\delta_1]'$.

$$
\begin{aligned}
  \mathbb{E}[\mathcal W_{it}|\mathcal W_{it-1}]=&\\
  \mathbb{E}[\omega_{it}|\mathcal W_{it-1}]=&\delta_0+\delta_1\mathbb{E}[\omega_{it-1}+(1-\beta)\varepsilon^Y_{it-1}|\mathcal W_{it-1}]\\
  &-\mathbb{E}[(1-\beta)\varepsilon^Y_{it}|\mathcal W_{it-1}]
  +\mathbb{E}[\eta_{it}|\mathcal W_{it-1}]\\
  =&\delta_0+\delta_1\mathbb{E}[\omega_{it-1}|\mathcal W_{it-1}]
\end{aligned}
$$

### Deconvoluting

But I can go further and recover the densities of tax evasion and productivity at every period. The key insight is that from the 1st stage, I also learn the distribution $m$ of $\varepsilon^Y_{it}$. Hence, I can use non-parametric density deconvolution methods. 

For completeness, I reproduce a result from probability theory that allows me to pursue these techniques.

::: {#def-deconv}

The density of the sum of two \emph{independent} random variables is equal to the \emph{convolution} of the densities of both addends; hence

$$h^d = f^d*m = \int f^d(\mathcal Z^d - \varepsilon^Y)m(\varepsilon^Y)d\varepsilon^y$$

where $h^d$ is the density of $\mathcal Z^d\in \{\mathcal{E,X,W}\}$ (Meister, 2009)

:::

The result holds by definition for productivity and true inputs, and by assumption \ref{ass-ind} for tax evasion.

Intuitively, for every $n$-th moment $\mathbb{E}[(\varepsilon^{Y}_{it})^n|S_{it}>s]=\mathbb{E}[(\varepsilon^{Y}_{it})^n|t]=\mathbb{E}[(\varepsilon^{Y}_{it})^n]$. Therefore, I can get any moment of the tax evasion $\varepsilon^M_{it}$ distribution $\forall t\in T$. For example,

$$
\begin{aligned}
  \mathbb{E}[\mathcal E_{it}|t]&=\mathbb{E}[\varepsilon^M_{it}|t]-\mathbb{E}[\varepsilon^Y_{it}]=\mathbb{E}[\varepsilon^M_{it}|t] \\
  \\
  \mathbb{Var}[\mathcal E_{it}|t]&=\mathbb{Var}[\varepsilon^M_{it}|t]
  +\underbrace{\mathbb{Var}[\varepsilon^Y_{it}]}_{known}\\
\end{aligned}
$$

Therefore, I can recover the distribution of tax evasion and how it has changed over time. Furthermore, I can do the same with true inputs $M_{it}^*$ and productivity $\omega_{it}$.

Moreover, I can get any mixed moment $\mathbb{E}[(\mathcal{Z}^c, \mathcal{Z}^d)^n|t]$ and learn how tax evasion changes with productivity, for instance, and how this relationship has evolved.

$$
\mathbb{Cov}[\mathcal{E}_{it},\mathcal{W}_{it}|t]=\mathbb{E}[\varepsilon^M_{it}\omega_{it}|t]
-\underbrace{
(1-\beta)\mathbb{E}[(\varepsilon^{Y}_{it})^2]-\mathbb{E}[\varepsilon^M_{it}|t]\mathbb{E}[\omega_{it}|t]}_{
known
}
$$
