## Identification Strategy {#sec-id-strat}

Because the firms' optimization decisions depend on the fiscal environment, the identification strategy should be motivated by the fiscal environment $\Gamma$. In particular, the identification strategy will be as good as how well we can tell apart a subset of firms that have the highest incentive to not evade. For example, in the case of Spain, the firms above the revenue LTU threshold. In the case of Colombia, the corporations.


::: {.Assumption #ass-non-ev}
#### Non-Evaders
Based on the fiscal environment $\Gamma$, the researcher can identify a subset of firms $\theta_i\in\Theta^{NE}\subset \Theta$ that does not evade taxes by overreporting inputs.
:::

For those firms, then $\mathbb{E}[e_{it}|\theta_i\in\Theta^{NE}]=0$

In addition, I impose the following timing assumption.

::: {.Assumption #ass-ind title="Independence" number="II"}
Firms choose overreporting $e_{it}$ *before *the output shock $\varepsilon_{it}$
:::

Assumption \ref{ass-ind} implies that input overreporting is independent of the current period output shock, $e_{it} \perp \varepsilon_{it}$. In the literature is not rare to assume that the output shock is not part of the information set of the firms, $\varepsilon_{it}\not\in \mathcal{I}_t$ [@Gandhi2020]. Timing and information set assumptions are not uncommon for identification strategies in production functions and demand estimation [@Ackerberg2021; @Ackerberg2019].

### Identifying the production function parameters 

The econometrician observes then the overreported inputs in the data, $M_{it}=M^*_{it}\exp(e_{it})$[^linear-exp]. Assume the production function is Cobb-Douglas, $G(M^*_{it}, K_{it}, L_{it})\exp(\omega_{it}+\varepsilon_{it})=M^{*\beta}_{it}K_{it}^{\alpha_K}L_{it}^{\alpha_L}\exp(\omega_{it}+\varepsilon_{it})$. Then, for the case of Colombia, @eq-foc:ind applies since the type of firms is the juridical organization and the non-evaders are Corporations. By multiplying both sides by the intermediate inputs and dividing by the output, we get

[^linear-exp]: Note we can always rewrite $M^*+e=M^*\exp\{a\}$, then $\exp\{a\}=\frac{e}{M^*}+1$.

$$
\begin{aligned}
    \ln\left(\frac{\rho_t M^*_{it}}{P_{t}Y_{it}}\right)+e_{it}&=\ln\beta + \ln \mathcal{E}- \varepsilon_{it} \\
    &\equiv \ln D^{\mathcal{E}}- \varepsilon_{it} 
\end{aligned}
$$ {#eq-foc-cd}


where, $\mathcal{E}\equiv \mathbb{E}[\exp(\varepsilon_{it})|\mathcal{I}_{it}]=\mathbb{E}[\exp(\varepsilon_{it})]$. 

We can use @eq-foc-cd and assumption \ref{ass-non-ev} to recover the production function parameter $\beta$

$$
    \mathbb{E}\left[\ln\left(\frac{\rho_t M^*_{it}}{P_{t}Y_{it}}\right)\Bigg| \Theta^{NE}\right]=\ln D^{\mathcal{E}}
$$ {#eq-foc-cd-exp}

The constant $\mathcal{E}$ is also identified [@Gandhi2020],

$$
\mathcal{E}=\mathbb{E}\left[\exp\left(\ln D^{\mathcal{E}}- \ln\left(\frac{\rho_t M^*_{it}}{P_{t}Y_{it}}\right)\right)|\theta^{NE}\right]=\mathbb{E}\left[\exp(\varepsilon_{it})|\theta^{NE}\right]=\mathbb{E}[\exp(\varepsilon_{it})]
$$ {#eq-id-E}

and, thus, the output elasticity of input, $\beta$, is also identified,

$$
\beta=\exp\left(\ln D^{\mathcal{E}}-\ln\mathcal{E}\right).
$$ {#eq-id-beta}

### Identifying Tax Evasion

Having recovered both the flexible input elasticity, $\beta$, and the constant $\mathcal{E}$, for all firms, I can form the following variable using observed data.

$$
\begin{aligned}
    \mathcal V_{it}\equiv&\ln\left(\frac{\rho_t M_{it}}{P_{t}Y_{it}}\right)-\ln\beta -\ln\mathcal{E}\notag \\
    &=\ln\left(\frac{\rho_tM^*_{it}}{P_{t}Y_{it}}\right)-\ln\beta-\ln\mathcal{E}+e_{it} \notag \\
    &=-\varepsilon_{it} +e_{it}
\end{aligned}
$$ {#eq-ob-ev}

Tax evasion therefore can be recovered up to an independent random variable. We can do better however. By assumption \ref{ass-ind}, the tax evasion, $\varepsilon_{it}$ ,is independent of $e_{it}$. Note that, from @eq-foc-cd, we also recovered $f_{\varepsilon}(\varepsilon)$ the distribution of $\varepsilon$. By using deconvolution methods, I can recover the tax evasion apart from the output shock.

In particular, from probability theory,

::: {.Definition #def-conv title="Convolution"}

The density of the sum of two **independent** random variables is equal to the **convolution** of the densities of both addends; hence

$$
h = f*m = \int f(\mathcal Z - \varepsilon)m(\varepsilon)d\varepsilon
$$

where $f$ is the density of $\mathcal Z$ (Meister, 2009)

:::

### Identifying Productivity

Here, I show how to recover the rest of the parameters of the production function, including productivity and its Markov process. We can do it in several ways, depending on our object of interest.

In the literature, it is not uncommon to assume that productivity follows a Markov process. That is, 

$$
    \omega_{it}=h(\omega_{it-1})+\eta_{it}
$$ {#eq-prod-markov}

Let $\ln X_{it}=x_{it}$. With @eq-ob-ev, we can form the following observed variable,

$$
\begin{aligned}
    \mathcal W_{it} & \equiv y_{it} - \beta (m_{it}-\mathcal{V}_{it})\\
    & = y_{it} - \beta (m^*_{it}+e_{it}-e_{it}+\varepsilon_{it})\\
    % & = y_{it} - \beta (m^*_{it}+\varepsilon_{it})\\
    & = y_{it} - \beta m^*_{it}-\beta\varepsilon_{it}\\
    & = \alpha_K k_{it}+\alpha_L l_{it}+\omega_{it}+(1-\beta)\varepsilon_{it}
\end{aligned}
$$ {#eq-big-w}

Here, intuitively, we are trading unobservables, the unobserved tax evasion for the output shock, just to make our lives easier. We could have use use directly $m^*$ since we know the distribution of tax evasion $e$, which is equivalent to the distribution of $f_{m^*|m}(m^*|m)$. Also note that is it not necessary to learn tax evasion to recover productivity. This is useful if a practicioner is only interested in productivity and not on tax evasion.

By replacing $\omega_{it}$ from @eq-big-w in @eq-prod-markov, we get

$$
\begin{aligned}
    \mathcal W_{it}=(1-\beta)\varepsilon_{it}+\alpha_K k_{it}+\alpha_L l_{it}+h(\mathcal W_{it-1}-(1-\beta)\varepsilon_{it-1}-\alpha_K k_{it-1}-\alpha_L l_{it-1})+\eta_{it}
\end{aligned}
$$ {#eq-big-w-reg}

If $h(\xi)=\delta_0 +\delta_1\xi$, to learn $\alpha$ and $h$, we need to find instruments $Z$ such that,

$$
\mathbb{E}[\eta_{it}+(1-\beta)\varepsilon_{it}+\delta_1(1-\beta)\varepsilon_{it-1}|Z]=0.
$$ {#eq-eta-moments}

Alternatively, when $h$ is non-linear,
$$
\begin{aligned}    
 \mathbb{E}[&\mathcal{W}_{it}|Z_{it}]\\
 &=\alpha_K k_{it}+\alpha_L l_{it}\\
 &+\mathbb{E}\left[ h(\mathcal W_{it-1}-(1-\beta)\varepsilon_{it-1}-\alpha_K k_{it-1}-\alpha_L l_{it-1})|Z_{it}\right]\\
 &=\alpha_K k_{it}+\alpha_L l_{it}\\
 &+\int\int h(\mathcal W_{it-1}-(1-\beta)\varepsilon_{it-1}-\alpha_K k_{it-1}-\alpha_L l_{it-1})f_{\mathcal{W}_{it-1},\varepsilon_{it-1}}(\mathcal{W}_{it-1},\varepsilon_{it-1}|Z_{it})d\mathcal{W}_{it-1}d\varepsilon_{it-1}\\
  &=\alpha_K k_{it}+\alpha_L l_{it}\\
 &+\int\int h(\mathcal W_{it-1}-(1-\beta)\varepsilon_{it-1}-\alpha_K k_{it-1}-\alpha_L l_{it-1})f_{\mathcal{W}_{it-1}}(\mathcal{W}_{it-1}|Z_{it},\varepsilon_{it-1})f_{\varepsilon_{it-1}}(\varepsilon_{it-1}|Z_{it})d\mathcal{W}_{it-1}d\varepsilon_{it-1}\\
  &=\alpha_K k_{it}+\alpha_L l_{it}\\
 &+\int\int h(\mathcal W_{it-1}-(1-\beta)\varepsilon_{it-1}-\alpha_K k_{it-1}-\alpha_L l_{it-1})f_{\varepsilon_{it-1}}(\varepsilon_{it-1})f_{\mathcal{W}_{it-1}}(\mathcal{W}_{it-1}|Z_{it},\varepsilon_{it-1})d\varepsilon_{it-1} d\mathcal{W}_{it-1}\\
 &=\alpha_K k_{it}+\alpha_L l_{it}\\
 &+\mathbb{E}\left[\int h(\mathcal W_{it-1}-(1-\beta)\varepsilon_{it-1}-\alpha_K k_{it-1}-\alpha_L l_{it-1})f_{\varepsilon_{it-1}}(\varepsilon_{it-1})d\varepsilon_{it-1}|Z_{it},\varepsilon_{it-1}\right]\\
%   &=\alpha_K k_{it}+\alpha_L l_{it}\\
%  &+\int h(\mathcal W_{it-1}-(1-\beta)\varepsilon_{it-1}-\alpha_K k_{it-1}-\alpha_L l_{it-1})f_{\mathcal{W}_{it}}(\mathcal{W}_{it}|Z_{it})d\mathcal{W}_{it}\\
% &=\alpha_K k_{it}+\alpha_L l_{it}+\mathbb{E}\left[ h(\mathcal W_{it-1}-(1-\beta)\varepsilon_{it-1}-\alpha_K k_{it-1}-\alpha_L l_{it-1})|Z_{it}\right]\\
% &=\alpha_K k_{it}+\alpha_L l_{it}+h(\mathcal W_{it-1}-(1-\beta)\varepsilon_{it-1}-\alpha_K k_{it-1}-\alpha_L l_{it-1})
 &=\alpha_K k_{it}+\alpha_L l_{it}+\mathbb{E}\left[\mathbb{E}_{\varepsilon_{t-1}}[ h(\mathcal W_{it-1}-(1-\beta)\varepsilon_{it-1}-\alpha_K k_{it-1}-\alpha_L l_{it-1})]|Z_{it},\varepsilon_{t-1}\right]\\
\end{aligned}
$$


The first line follows from the orthogonality of the output shock of the current period $\mathbb{E}[\varepsilon_{it}|Z_{it}]=0$. The second line uses the definition of expectation. The third line decomposes the joint distribution of $\mathcal W_{it-1}$ and $\varepsilon_{it-1}$ using the Bayes' theorem. The fourth and fifth lines follow from the independence of the output shock of the previous period $\varepsilon_{it-1}$ with respect to $Z_{it}$ and the interchangeability of integrals. The sixth line uses the definition of the expectation again. Thus, $\alpha$ and $h$ are identified. Line six shows that we can take the expectation of $h(\cdot)$ with respect $\varepsilon_{t-1}$ and then form the moments using the intstruments $Z_{it}$. In principle, we can also use $\varepsilon_{it-1}$ as instrument. This identification works great for [polynomials](https://github.com/hans-mtz/tax_evasion_productivity/blob/main/Paper/integral.pdf).

@tbl-orth displays candidates for $Z$

|     |  Orthogonality     |
|:----|:----------------:|
|$\eta_{it}$ | $k_{it},l_{it},\varepsilon_{it}$, $k_{it-1},l_{it-1},\varepsilon_{it-1},\omega_{it-1},\mathcal{W}_{it-1},m_{it-1},m^*_{it-1}$|
| $\varepsilon_{it}$ | $k_{it},l_{it},\omega_{it},m_{it},m^*_{it},\eta_{it}$, $k_{it-1},l_{it-1},\varepsilon_{it-1},\omega_{it-1},\mathcal{W}_{it-1},m_{it-1},m^*_{it-1}$|
| $\varepsilon_{it-1}$ | $k_{it},l_{it},\omega_{it},\varepsilon_{it},m_{it},m^*_{it},\eta_{it}$, $k_{it-1},l_{it-1},\omega_{it-1},\mathcal{W}_{it},m_{it-1},m^*_{it-1}$| 

: Orthogonality by Residuals {#tbl-orth}


<!-- Orthoganility of $\eta_{it}$ follows from ($k_{it-1},l_{it-1},\mathcal{W}_{it-1}$) being known to the firm at period $t-1$, and ($k_{it},l_{it}$) being predetermined. -->

<!-- To see how, note that even though we only recoverd the output shock distribution from the first stage and cannot form directly the regression in @eq-big-w-reg, we can still use the moments implied by @eq-eta-moments. Let $Z_{it}=\{k_{it},l_{it},k_{it-1},l_{it-1},\mathcal{W}_{it-1}\}$, -->

The ideal instruments are $Z_{it}=\{k_{it},l_{it},k_{it-1},l_{it-1}, m_{it-1}\}$.

How many instruments are needed in practice? I use one per element in constant of integration to be just-identified. Then, for Cobb-Douglas case, I use $Z_{it}=\{k_{it},l_{it}\}$, with $h$ as a third degree polynomial.


Once the paramaters of the production function are identified, we can use the following observed variable to recover $\omega_{it}$

$$
\begin{aligned}
    \widetilde{\mathcal W_{it}} & \equiv \mathcal W_{it} - \alpha_K k_{it}-\alpha_L l_{it}\\
    & = \omega_{it}+(1-\beta)\varepsilon_{it}
\end{aligned}
$$ {#eq-big-w}

### Translog Production Function

To identify tax evasion and relaxing the assumption of a CD production function, we would need a flexible input for which firms have no inventives to overreport. Firms might face flexible inputs that they cannot deduct from their VAT or CIT, for example. If this is the case, then firms would have no incentives to overreport non-deductible flexible inputs. 

Assume now that $L_{it}$ is a non-deductible flexible input and, without loss of generality, there are only two inputs ($L_{it}, M_{it}$). Let's assume the production function is now *translog*. We have, 

$$
 \ln G(l,m)=\beta_0m_{it}+\beta_1m_{it}l_{it}+\beta_2m_{it}m_{it}+\beta_3l_{it}+\beta_4l_{it}l_{it}
$$ 

Then, equation @eq-foc:non-deduct becomes

$$
\begin{aligned}
    s_{it}^{L}&=\ln \left(\beta_3+2\beta_4l_{it}+\beta_1(m^*_{it}+e_{it})\right) + \ln \mathcal{E}- \varepsilon_{it} \\
    &\equiv \ln D^{\mathcal{E}}(l_{it},m^*_{it}+e_{it})- \varepsilon_{it} 
\end{aligned}
$$ {#eq-translog-share}

where $s_{it}^{L} \equiv\ln\left(\frac{w_t L_{it}}{(1-\tau)P_{t}Y_{it}}\right)$. 

Note that by assumption \ref{ass-non-ev}, $D^{\mathcal{E}}$ and the density of $\varepsilon$ are still identified. 

#### Testing for Tax Evasion

We can design a test for tax evasion by forming the analog of @eq-ob-ev,

$$
\begin{aligned}
\mathcal{V}_{it}^{L} =&\ln D^{\mathcal{E}}(l_{it},m_{it}^*+e_{it})-s_{it}^L\\
    =&\ln D^{\mathcal{E}}(l_{it},m_{it}^*+e_{it})-\ln D^{\mathcal{E}}(l_{it},m_{it}^*)+\varepsilon_{it}\\
    =&\ln\left(\frac{D^{\mathcal{E}}(l_{it},m_{it}^*+e_{it})}{D^{\mathcal{E}}(l_{it},m_{it}^*)}\right)+\varepsilon_{it}\\
\end{aligned}
$$


Note that $\ln\left(\frac{D^{\mathcal{E}}(l,m^*+e)}{D^{\mathcal{E}}(l,m^*)}\right)\ge0$ is always positive because $e_{it}\ge0$ and $D^{\mathcal{E}}$ is strictly increasing in $m$. Thus, $\frac{D^{\mathcal{E}}(l,m^*+e)}{D^{\mathcal{E}}(l,m^*)}\ge1$.

#### Identifying Tax Evasion

Once we recovered the parameters of @eq-translog-share, we can invert it to solve for the true inputs $m^*$ as a function of observed data and the output. Then, the difference between the observed and true inputs is by definition the tax evasion by overreporting.

$$
\begin{aligned}
    m_{it}-&D^{-1}(\exp(s^L_{it}-\ln\mathcal{E}-\varepsilon_{it}),l_{it})\\
    &= m_{it}^*+e_{it} -D^{-1}(\exp(s^L_{it}-\ln\mathcal{E}-\varepsilon_{it}),l_{it})\\
    &= m_{it}^*+e_{it} -D^{-1}(D(l_{it},m_{it}^*),l_{it})\\
    &=e_{it}
\end{aligned}
$$

Again, having recovered the distribution of the output shock $f_{\varepsilon}(\varepsilon)$, we can use deconvolution techniques to learn the distribution of $e$. In particular, to learn the p.d.f of tax evasion $f_e(e)$, we can deconvolute it by

$$
    \int f_e(m_{it}-D^{-1}(\exp(s^L_{it}-\ln\mathcal{E}-\varepsilon_{it}),l_{it})) f_{\varepsilon}(\varepsilon)d\varepsilon
$$

### Non-Parametric Identification of Tax Evasion

The previous result also suggests a non-parametric identification strategy, as long as $D^{\mathcal{E}}$ is monotonic in $m$. This identification strategy is analogous to @Hu2022b, where the authors also require monotonicity and independence to recover a nonparametric function of $m^*$ with nonclassical measurement error. 

In our case, intuitively, if we know the density of $\varepsilon$ and the function $D^{\mathcal{E}}$, the variation left is due to $e$, which can be recovered as long as we can vary $D^{\mathcal{E}}$ by moving $e$.

To see why the non-deductible flexible input is needed to identify tax evasion consider the following. Suppose that only the input $M$ is flexible and deductible.

$$
\ln\left(\frac{\rho M}{PY}\right)=\ln D^{\mathcal{E}}(K,L,M)-\varepsilon
$$

$D^{\mathcal{E}}(K,L,M)$ is still identified by assumption \ref{ass-non-ev}, however, when we form the analogous of @eq-ob-ev, we now have

$$
\begin{aligned}
\ln\left(\frac{\rho M}{PY}\right)-&\ln D^{\mathcal{E}}(K,L,M)=\\
&\ln\left(\frac{\rho(M^*+e)}{PY}\right)-\ln D^{\mathcal{E}}(K,L,M^*+e)\\
=&\ln\left(\frac{\rho(M^*+e)}{PY}\right)-\ln D^{\mathcal{E}}(K,L,M^*+e)\\
&+\left[\ln\left(\frac{\rho M^*}{PY}\right)-\ln D^{\mathcal{E}}(K,L,M^*)\right]\\
&-\left[\ln\left(\frac{\rho M^*}{PY}\right)-\ln D^{\mathcal{E}}(K,L,M^*)\right] \\
=&\ln\left(\frac{\rho M^*}{PY}\right)-\ln D^{\mathcal{E}}(K,L,M^*) \\
&+\left[\ln\left(\frac{\rho(M^*+e)}{PY}\right)-\ln\left(\frac{\rho(M^*)}{PY}\right)\right]\\
&-\left[\ln D^{\mathcal{E}}(K,L,M^*+e)-\ln D^{\mathcal{E}}(K,L,M^*)\right]\\
=& -\varepsilon \\
&+\left[\ln D^{\mathcal{E}}(K,L,M^*+e)-\varepsilon-\ln D^{\mathcal{E}}(K,L,M^*)+\varepsilon\right]\\
&-\left[\ln D^{\mathcal{E}}(K,L,M^*+e)-\ln D^{\mathcal{E}}(K,L,M^*)\right]\\
=& -\varepsilon(K,L,M^*)
\end{aligned}
$$

Now, we are not able to separate the variation of $\varepsilon$ from $e$.