# Data

I will use annual survey data at the establishment level for manufacturing firms in Latin America, namely, Ecuador, Colombia, Chile, and Mexico. I will also use anonymized annual tax declarations from firms in Ecuador and Mexico. I do not expect to link the survey data with the tax records, but to learn moments from the tax records for my estimation. Furthermore, the tax records are not needed, they are intended for validation purposes only. Below I describe some data bases I will use.

The anonymized records come from the tax agency in Mexico [*Secretaria de Administración Tributaria* (SAT)](http://omawww.sat.gob.mx/cifras_sat/Paginas/inicio.html). The data I'm interested in is described in @Zumaya2021. Nevertheless, there is anonymized sample data available from the SAT. These tax records include the annual tax declarations of a sample of 520,000-720,000 firms, between 2010-2015, depending on the year. The data includes information about the total income, profit/losses before taxes and before paying the share of profits to employees (PTU), taxes on profits (ISR), and credits and reductions for different reasons, e.g., reductions for Maquiladoras, R&D credits, among others. It also includes some firm characteristics like country region, broad industry classification, e.g, service, commerce, manufacturing, etc., and age. Table \ref{tab:tax_table} describes the summary statistics for this data.

\input{tables/tax_table} 

The Manufacturing Industry Annual Survey (*Encuesta Anual de la Industria Manufacturera*, EAIM) data is collected by the National Institute of Statistics and Geography (INEGI) of Mexico and contains information at the establishment level on manufacturing firms. The survey classifies the manufacturing sector according to the North American Industrial Classification System (NAICS, 2013). The survey covers the years 2013-2020 and it is representative at the national level by industry sector, disaggregated at the subsector, branch, and economic activity class according to the 2013 NAICS. The data can only be accessed by remote estimation or on-site at the INEGI data laboratories in Mexico City.

The INEGI-EAIM includes the following variables: sales value, production value, intermediate inputs —raw materials, packaging, fuel, energy— value, labor quantity and total wage bill, capital value, and stock of raw materials, work-in-process, and production at the end of the year. Table \ref{tab:eaim_table} shows the summary statistics for a small sample of observations publicly available to test programming code before submitting it to remote processing at INEGI.

\input{tables/eaim_table}

The Colombian Annual Manufacturer Survey (*Encuesta Anual de Manufactura*, EAM) recollects information on manufacturing plants in Colombia with a minimum income of 500 million Colombian pesos (COP) or 10 employees. The EAM includes the production value, sales value, raw materials consumed and its value, employees and payroll, as well as the book value of capital. The table \ref{tab:col_table} present the summary statistics of the 2018 survey.

\input{tables/col_table}


