## Colombia 1981-1991

### Colombian Corporate Tax System

The relevant corporate taxes for input overreporting in Colombia during this period are the Corporate Income Tax (CIT) and the Sales Tax. The Sales Tax gradually transformed into a kind of Value-Added Tax (VAT). Also relevant for the CIT are the different juridical organizations that exist in Colombia. 

This period was characterized by high levels of overall tax evasion [@Sanchez1994]. The fiscal rules had a system of penalties and interest that encouraged false and delinquent returns [@McLure1989]. The fiscal authority was characterized by having an inefficient auditing system, being overburdened, and legal loopholes [@Perry1990].

#### Juridical Organizations

In Colombia, there are five types of juridical organizations: Corporations, Partnerships, Limited Liability Companies, and Individual Proprietorships.

Corporations (*sociedad anónima*) are the typical associations of capital. They are the counterpart of the US corporation. The capital of a corporation is provided by the shareholders (no less than 5) and is divided into tradable shares of equal value. Shareholders' liability is limited to the capital contributed. Corporations are subject to the Superintendent of Corporations and are closely supervised, being required to have an auditor.

Joint Stock Companies (*sociedad en comandita por acciones*) comprises two or more managing partners who are jointly and severally liable, and five or more limited partners whose liability is limited to their respective contributions. Joint Stock Companies are taxed as Corporations. Its shares are tradable, like the shares of Corporations. 

Partnerships are associations of two or more persons. Partners are jointly and severally liable for the partnership's operations. Partnerships include general partnerships (*sociedad colectiva*), de Facto partnerships (*sociedades de hecho*), and ordinary limited partnerships (*sociedad en comandita simple*).

A limited liability company (*sociedad de responsabilidad limitada*) is an association of two or more persons —not exceeding 20 (Fiscal Survey) or 25 (1992 *EAM* survey documents)—, whose shares cannot be traded. The personal liability of the partners is limited to the capital contributed. The Limited Liability Company is quite important in Colombia (Fiscal Survey).

Finally, proprietorships are individuals (natural persons) who allocate part of their assets to conduct commercial activities.

There are other juridical organizations in the data that will be excluded from the final analysis. These organizations are non-profit, like cooperatives and community enterprises, or state industrial enterprises, the proceeds of which come from taxes, fees, or special contributions.

#### Corporate Income tax

The juridical organizations were subject to different Corporate Income Tax rates. Corporations were taxed at a fixed rate of 40%, while Partnerships and Limited Liability companies at 20%. Individual proprietors were subject to the graduated Individual Tax Schedule consisting of 56 rates, ranging from 0.50 to 51 percent. 

Corporations were taxed on their distributed dividends, while partnerships and limited liability companies were taxed on their profits, whether or not distributed. Owners of juridical organizations were double taxed, at the firm and the individual level, whereas the income of proprietorships was taxed only once, at the individual level. 

Since 1974, individuals and juridical organizations, except for limited liability companies, were subject to the minimum presumptive income. Rent (income and profits) was presumed to be no less than 8 percent of net wealth (assets less depreciation, real estate, livestock, securities).

Certain industries like airlines, publishing, and reforestation sectors, and various activities in selected regions (primarily "frontier" and other less developed ones) had their income tax exempted, limited, or reduced.

::: {#tbl-jo-sum-tbl}

| Organization | Corporate Income Tax | Liability | Capital | Owners |
|:----------------------:|:---:|:---------:|:-------:|:----------:|
| Corporation           | 40% (on distributed dividends) | Limited to capital participation | Tradable capital shares | $N\ge5$ |
| Limited Co. | 20% (on profits) | Limited to capital participation | Non-tradable capital shares | $2\le N \le 20 (25)$ |
| Partnership | 20% (on profits) | Full | Not a capital association | $N\ge2$ |
| Proprietorship | Individual Income Tax | Full | Owner | $N=1$ |


Juridical Organizations in Colombia (1980s), A Summary 

:::



#### Sales taxes

Sales taxes were originally targeted at the manufacturing sector on finished goods and imports. Since 1974, manufacturers were allowed to credit taxes paid on any purchase made by the firm, except the acquisition of capital goods [@Perry1990]. The credits worked through a system of refunds. Consequently, the tax became a kind of value-added tax (VAT). 

The basic rate was 15 percent. There was also a preferential rate of 6 percent for certain industries like clothing, footwear, and major inputs used for building popular housing, and a rate of 35 percent for luxury goods. Exports, foodstuff, drugs, and textbooks were excluded from the beginning. Also excluded were inputs, transportation equipment, agricultural machinery, and equipment.

#### Discussion

From Colombia's tax system, we can conclude that corporations are the least likely to evade taxes by misreporting because of at least three reasons. One, the Superintendent of Corporations closely monitored corporations by requiring them to have an auditor. In the model, this implies that the probability of detection is higher for them. Second, free tradable shares impose an incentive to be profitable because the market value of the shares might be negatively affected otherwise. In other words, if a corporation fakely reports lower profits, the value of its shares would likely decrease scaring away shareholders and potential investors. Joint stock companies have freely tradable shares too. Three, corporations pay CIT on distributed dividends, not on profits as Partnerships and LLCs did. Corporations have an additional margin regarding the income tax they pay because they decide when to pay dividends. This might generate other types of incentives that might be influenced by the corporation's policy regarding their dividends and the demands of their shareholders. On the other hand, Proprietorships and LLCs are subject to the incentive to evade CIT by artificially reducing their profits.

Moreover, Proprietorships, Partnerships, and Limited Companies had incentives to overreport inputs to evade VAT and CIT. The incentives to evade varied across industries because the sales tax rate differed between industries. The incentives to evade also varied within industry sectors because juridical organizations within an industry were subject to different CIT rates. There were additional sources of variation depending on the firm's location due to local exemptions and sales composition (inputs to other firms, to consumers, to the foreign market).

Lastly, Individual proprietorships were likely to bunch at the individual income thresholds because they were subject to individual income tax which was increasing by brackets.


