## Stage-2 ELVIS driver -----------------------------------------------------
## theta = (lambda, delta0, delta1, delta2, sigma2_psi), unincorp firms only,
## moment system from Paper/sections/9999-elvis.qmd "Applying ELVIS to stage
## 2 alone" + CLAUDE.md's 2026-08-28 "Stage-2 moment system, finalized" entry
## (15 moments, see Code/Rcpp/1200-stage2-elvis.cpp's header for the full
## list). Compiled worker does the per-firm Metropolis-tilted-average
## simulation (mh_tilted_average_cpp); everything else (CUE objective, BOBYQA
## search, the lambda grid) is R, following AK2020's own split (NLopt/BOBYQA
## for the smooth block, theta's "difficult" dimension gridded).
##
## lambda is gridded, not searched directly, because it's the one parameter
## that changes the SUPPORT of the latent M (not just a smooth reweighting):
## feasibility requires M*_it > 1/(2*lambda) for every firm used at that grid
## point -- (delta0,delta1,delta2,sigma2_psi,gamma) is the smooth block,
## jointly optimized via BOBYQA for each lambda.
##
## 2026-08-28 moment-system redesign: dropped the psi*lag_k/psi*lag_l/psi*
## (cross-instrument) spare-instrument rows entirely (Z_CANDIDATES, the old
## z_cols machinery) -- replaced by psi*ln(M)/psi*(ln M)^2 (more direct: M is
## "true inputs" itself, not a proxy, and no observations lost to lagging),
## plus a new eps-heterogeneity block (rows 7-10 in the .cpp, matched to each
## firm's own sic_3 via Code/Products/1206-stage2-eps-targets.RData -- CORP
## epsilon's variance is NOT homogeneous across industries, Bartlett K^2=920,
## p<2e-16, so a single pooled target would misspecify most industries), and
## a new sigma2_psi nuisance parameter (rows 11-14, a heteroskedasticity-in-
## psi block). d_g is now a fixed 15 (was 1+length(z_cols)+3=7), and the
## smooth block grew from 3 to 4 parameters. See CLAUDE.md for the full
## design discussion and what was considered and dropped (psi*e; the
## redundant psi*(eps^2-var) alongside psi*eps_c^2).
##
## corner_mode ("drop" vs "include_zero"), added 2026-08-27: tau_P_it==0
## firms (~10% of unincorp obs) are a genuine MB(e)=0-for-every-e corner, not
## data noise. "drop" excludes them entirely. "include_zero" keeps them with
## a known M=Mstar (e=0) contributing only the psi-free rows (eps*om and the
## eps-only CORP-target rows) -- see the .cpp header for exactly which rows.
##
## Random-number handling in the C++ worker (2026-08-27): each firm's WHOLE
## random sequence is generated by a C++-side RNG reseeded per firm as
## base_seed+row_id -- identical across every (theta,gamma) evaluation. The
## chain also discards an initial n_burn steps before averaging over n_keep.

library(tidyverse)
library(Rcpp)
library(nloptr)
library(RcppParallel)

source("Code/Deconvolution/utils-cli.R")
sourceCpp("Code/Rcpp/1200-stage2-elvis.cpp")
load("Code/Products/1200-stage2-data.RData")            # stage2_data
load("Code/Products/1205-stage2-warmstart.RData")       # warmstart_lag_m, warmstart_lag2W
load("Code/Products/1206-stage2-eps-targets.RData")     # eps_targets

set.seed(20260825)   # no longer drives estimation randomness (that's C++-side, seeded per firm by row_id) --
                      # harmless to keep, would only matter if this file grew its own R-level random draws

## %% Build the estimation sample for one ins, joined with its eps targets --

build_run_sample <- function(ins_choice, data = stage2_data, corner_mode = c("drop", "include_zero")) {
    corner_mode <- match.arg(corner_mode)

    base <- data %>%
        dplyr::filter(ins == ins_choice, !corp)

    interior <- base %>%
        dplyr::filter(is.finite(sales_tax_rate_purchases), sales_tax_rate_purchases > 0) %>%
        mutate(corner = 0L)

    out <- if (corner_mode == "drop") {
        interior
    } else {
        corner_obs <- base %>%
            dplyr::filter(is.finite(sales_tax_rate_purchases), sales_tax_rate_purchases == 0) %>%
            mutate(corner = 1L)
        bind_rows(interior, corner_obs)
    }

    out %>%
        dplyr::select(plant, year, sic_3, M_star, cal_V, tilde_cal_W, sales_tax_rate_purchases, beta, corner) %>%
        dplyr::left_join(
            dplyr::filter(eps_targets, ins == ins_choice) %>% dplyr::select(sic_3, mu1, var, mu3),
            by = "sic_3"
        ) %>%
        dplyr::rename(eps_mu1 = mu1, eps_var = var, eps_mu3 = mu3)
}

## %% CUE objective: R does the (small, D_G=15-dimensional) linear algebra; --
## C++ only does the expensive per-firm simulation loop.
##
## par = (delta0, delta1, delta2, sigma2_psi, gamma[1:15]) -- 19 elements.
##
## Parallelized over firms INSIDE mh_tilted_average_cpp (2026-08-28, RcppParallel
## -- superseded an earlier R-level mclapply approach, see CLAUDE.md for the
## measured comparison): thread count is a process-global TBB scheduler
## setting via RcppParallel::setThreadOptions(), called once below from
## opt$n_cores, NOT passed per-call -- so this function is unchanged from a
## plain serial call site's perspective.

D_G <- 15

cue_objective <- function(par, lambda, dat, n_burn, n_keep) {
    delta0 <- par[1]; delta1 <- par[2]; delta2 <- par[3]; sigma2_psi <- par[4]
    gamma  <- par[-(1:4)]

    Ghat <- mh_tilted_average_cpp(
        dat$M_star, dat$cal_V, dat$tilde_cal_W, dat$sales_tax_rate_purchases,
        dat$eps_mu1, dat$eps_var, dat$eps_mu3,
        dat$.row_id, dat$beta, lambda, delta0, delta1, delta2, sigma2_psi, gamma, dat$corner,
        n_burn, n_keep
    )

    dvec  <- colMeans(Ghat)
    Omega <- cov(Ghat)
    eig   <- eigen(Omega, symmetric = TRUE)
    pos   <- eig$values > 1e-8 * max(eig$values)     # relative eigenvalue truncation (AK2020's objMCcu pattern)
    A     <- eig$vectors[, pos, drop = FALSE]
    d2    <- as.numeric(t(A) %*% dvec)
    V2    <- t(A) %*% Omega %*% A
    Omega_ginv <- solve(V2)

    0.5 * as.numeric(t(d2) %*% Omega_ginv %*% d2)
}

## %% One lambda grid point: filter to feasible firms, optimize (delta,gamma) --
##
## delta0-2, sigma2_psi, and gamma get SEPARATE box bounds: sigma2_psi is a
## variance (must stay strictly positive) so it gets its own asymmetric
## bound, not the +-DELTA_BOUND box the other 3 smooth params use. gamma has
## no natural economic scale (Lagrange multiplier on the moment vector), so
## its own wider box (2026-08-27 finding: some gamma components were landing
## within rounding of a too-tight +-20 box) is unrelated to this change.
DELTA_BOUND      <- 20
GAMMA_BOUND      <- 300   # widened 2026-08-29 from 100: several smoke-test cells under the new 15-moment
                          # system landed within rounding of 100 (max|gamma| up to 99.93) -- same instability
                          # signature as the 2026-08-27 finding that led to widening it from 20 to 100 back
                          # then. Checking whether cells keep climbing (real) or settle (was just the box).
SIGMA2_PSI_LOWER <- 1e-6
SIGMA2_PSI_UPPER <- 20      # same order as DELTA_BOUND; revisit once real fits give a sense of psi's scale

fit_one_lambda <- function(lambda, run_sample, n_burn, n_keep, par_init) {
    # feasibility (M*_it > 1/(2*lambda)) only binds for latent-M (corner==0) firms --
    # corner firms have a known M=Mstar (e=0) regardless of lambda, so always kept.
    dat <- run_sample %>% dplyr::filter(corner == 1 | M_star > 1 / (2 * lambda))
    n_dropped <- nrow(run_sample) - nrow(dat)

    if (nrow(dat) < 50) {
        return(list(lambda = lambda, value = NA, par = NA, n = nrow(dat), n_dropped = n_dropped,
                    convergence = NA, iter = NA, message = "too few obs"))
    }

    obj <- function(par) cue_objective(par, lambda, dat, n_burn, n_keep)

    res <- nloptr::bobyqa(
        x0 = par_init, fn = obj,
        lower = c(rep(-DELTA_BOUND, 3), SIGMA2_PSI_LOWER, rep(-GAMMA_BOUND, D_G)),
        upper = c(rep( DELTA_BOUND, 3), SIGMA2_PSI_UPPER, rep( GAMMA_BOUND, D_G))
    )

    list(lambda = lambda, value = res$value, par = res$par, n = nrow(dat), n_dropped = n_dropped,
         convergence = res$convergence, iter = res$iter, message = res$message)
}

## %% Data-driven lambda grid: from quantiles of M_star, not a fixed range --

build_lambda_grid <- function(run_sample, probs = c(0.9, 0.75, 0.5, 0.25, 0.1)) {
    e_max <- quantile(run_sample$M_star, probs = probs)
    1 / (2 * e_max)
}

## %% Run for one ins choice --------------------------------------------------

run_stage2_elvis <- function(ins_choice, warmstart, n_burn = 50, n_keep = 500,
                              grid_probs = c(0.9, 0.75, 0.5, 0.25, 0.1),
                              corner_mode = c("drop", "include_zero")) {
    corner_mode <- match.arg(corner_mode)
    run_sample <- build_run_sample(ins_choice, corner_mode = corner_mode) %>%
        mutate(.row_id = dplyr::row_number())
    lambda_grid <- sort(build_lambda_grid(dplyr::filter(run_sample, corner == 0), grid_probs))

    cat(sprintf("[%s, corner_mode=%s] n=%d (%d corner), n_burn=%d, n_keep=%d, lambda grid: %s\n",
                ins_choice, corner_mode, nrow(run_sample), sum(run_sample$corner), n_burn, n_keep,
                paste(signif(lambda_grid, 3), collapse = ", ")))

    # (delta0, delta1, delta2, sigma2_psi, gamma[1:D_G]) -- all 4 smooth-block
    # values now come from the warm start (2026-08-28 redesign: S-draw eps
    # sampling per firm, moment-shaped NLS on the stacked sample -- see
    # 1205-stage2-warmstart.R); gamma still starts at 0 (no warm-start signal
    # for the Lagrange multipliers).
    par_init <- c(
        warmstart$par[["delta0"]], warmstart$par[["delta1"]], warmstart$par[["delta2"]],
        warmstart$par[["sigma2_psi"]],
        rep(0, D_G)
    )

    fits <- vector("list", length(lambda_grid))
    for (i in seq_along(lambda_grid)) {
        fits[[i]] <- fit_one_lambda(lambda_grid[i], run_sample = run_sample,
                                     n_burn = n_burn, n_keep = n_keep, par_init = par_init)
        if (!is.na(fits[[i]]$value)) par_init <- fits[[i]]$par   # chain into the next (larger) lambda; skip on failure
    }

    for (f in fits) {
        cat(sprintf("  lambda=%.3g: n_used=%d (dropped %d), Lhat=%s, conv=%s, iter=%s\n",
                     f$lambda, f$n, f$n_dropped,
                     ifelse(is.na(f$value), "NA (too few obs)", signif(f$value, 4)),
                     f$convergence, f$iter))
    }
    fits
}

## %% One config per invocation -----------------------------------------------
## Each Rscript/R CMD BATCH invocation runs exactly ONE (ins, corner_mode,
## n_burn, n_keep, grid_probs) config, driven by CLI args (see utils-cli.R),
## and writes a self-labeled .RData product. run-stage2-elvis-sweep.sh
## launches all 4 (ins x corner_mode) configs in parallel.

WARMSTARTS <- list(lag_m = warmstart_lag_m, lag_2_cal_W = warmstart_lag2W)

## n_cores default is 1 (no parallelism unless asked for) -- deliberately
## conservative: run-stage2-elvis-sweep.sh already launches 4 configs (ins x
## corner_mode) as separate OS processes in parallel, so setting n_cores>1
## here TOO means n_cores x 4 threads/processes competing for this machine's
## 12 cores. Pick n_cores so that (n_cores x number of simultaneous configs)
## doesn't exceed available cores -- e.g. n_cores=3 per process if running
## the full 4-way sweep on a 12-core machine, or a much higher n_cores if
## running a single config standalone (not via the sweep script). This sets
## RcppParallel's thread pool ONCE (a process-global TBB scheduler setting,
## not a per-call argument), so it applies to every mh_tilted_average_cpp
## call made for the rest of this script's run.
DEFAULTS <- list(
    ins         = "lag_m",                          # "lag_m" | "lag_2_cal_W"
    corner_mode = "drop",                            # "drop" | "include_zero"
    n_burn      = 50,
    n_keep      = 500,
    grid_probs  = c(0.9, 0.75, 0.5, 0.25, 0.1),
    n_cores     = 1
)
opt <- parse_cli_args(DEFAULTS)
opt$n_cores <- as.integer(opt$n_cores)
stopifnot(
    opt$ins %in% names(WARMSTARTS),
    opt$corner_mode %in% c("drop", "include_zero")
)
log_run_header("1210-stage2-elvis-driver.R", opt)
RcppParallel::setThreadOptions(numThreads = opt$n_cores)

fits <- run_stage2_elvis(
    opt$ins, WARMSTARTS[[opt$ins]],
    n_burn = opt$n_burn, n_keep = opt$n_keep,
    grid_probs = opt$grid_probs, corner_mode = opt$corner_mode
)

tag <- sprintf("%s-%s-nburn%d-nkeep%d", opt$ins, opt$corner_mode, opt$n_burn, opt$n_keep)
out_file <- sprintf("Code/Products/1210-stage2-elvis-%s.RData", tag)
save(fits, opt, file = out_file)
cat(sprintf("Saved: %s\n", out_file))
