<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>counterfactual-pr-081026</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="08-counterfactual-pr-081026_files/libs/clipboard/clipboard.min.js"></script>
<script src="08-counterfactual-pr-081026_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="08-counterfactual-pr-081026_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="08-counterfactual-pr-081026_files/libs/quarto-html/popper.min.js"></script>
<script src="08-counterfactual-pr-081026_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="08-counterfactual-pr-081026_files/libs/quarto-html/anchor.min.js"></script>
<link href="08-counterfactual-pr-081026_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="08-counterfactual-pr-081026_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="08-counterfactual-pr-081026_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="08-counterfactual-pr-081026_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="08-counterfactual-pr-081026_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="proof-read-08-counterfactual.qmd-paragraph-1-l21-2026-10-08" class="level1">
<h1>Proof-read: 08-counterfactual.qmd, paragraph 1 (L21), 2026-10-08</h1>
<p>Audience: JMP/thesis (first-year PhD, economist outside public finance). Scope: Hans’s revised opening question, read against ch.&nbsp;2 (rate on purchases, net-of-tax price) and ch.&nbsp;8 P2–P4.</p>
<section id="errors-fix" class="level2">
<h2 class="anchored" data-anchor-id="errors-fix">Errors (fix)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 40%">
<col style="width: 28%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Sentence</th>
<th>Issue</th>
<th>Fix</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>“Larger ouput increases …”</td>
<td>typo</td>
<td>“output”</td>
</tr>
<tr class="even">
<td>2</td>
<td>“… because claimed deductions raise.”</td>
<td>“raise” is transitive; the intransitive verb is “rise”</td>
<td>“because claimed deductions rise”</td>
</tr>
<tr class="odd">
<td>3</td>
<td>“… on sales but larger materials …”</td>
<td>comma before “but” joining two independent clauses; “larger materials” (materials are not large, purchases are)</td>
<td>“…, but more materials lower revenue …”</td>
</tr>
<tr class="even">
<td>4</td>
<td>“And, how much of …”</td>
<td>no comma after a sentence-initial “And”; starting with “And” is informal</td>
<td>drop “And,” or join the two questions</td>
</tr>
</tbody>
</table>
</section>
<section id="consistency" class="level2">
<h2 class="anchored" data-anchor-id="consistency">Consistency</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Where</th>
<th>Issue</th>
<th>Suggestion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>5</td>
<td>last two sentences, “the tax rate” (twice)</td>
<td>the paragraph otherwise says “the rate” for the rate on purchases; “the tax rate” could be read as the rate on sales</td>
<td>“the rate”</td>
</tr>
<tr class="even">
<td>6</td>
<td>“changes in tax evasion”</td>
<td>the paragraph and chapter say “overreporting”</td>
<td>“firms overreporting more”</td>
</tr>
<tr class="odd">
<td>7</td>
<td>“the optimization of the firms adjusting to the new price ratio”</td>
<td>wordy; P2 and P3 call this “firms buying more or fewer materials”</td>
<td>“firms buying more materials”</td>
</tr>
<tr class="even">
<td>8</td>
<td>“the government’s revenue” vs “tax revenue” in the first sentence</td>
<td>variation; same object</td>
<td>“revenue” or “tax revenue” both times</td>
</tr>
</tbody>
</table>
</section>
<section id="structure-and-accuracy" class="level2">
<h2 class="anchored" data-anchor-id="structure-and-accuracy">Structure and accuracy</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Where</th>
<th>Issue</th>
<th>Suggestion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>9</td>
<td>first and penultimate sentences</td>
<td>both ask how revenue changes with the rate; the paragraph opens and closes with nearly the same question</td>
<td>keep the opening question as the hook, make the closing one the sharper version: “at the margin”, then the split</td>
</tr>
<tr class="even">
<td>10</td>
<td>last question</td>
<td>asks how the change in <strong>revenue</strong> splits between overreporting and materials, but P2 and P3 split <strong>claimed deductions</strong> (mechanical, materials, overreporting). The Results section will split revenue too (tbl-cf-revenue, input columns), so the question is answerable; the opener just answers it for claims</td>
<td>either ask the split for claimed deductions, or keep revenue and accept that P3 answers it through claims</td>
</tr>
<tr class="odd">
<td>11</td>
<td>“An increase in the rate also affects firms’ choice of true materials”</td>
<td>“affects” is vague when the direction is known</td>
<td>“raises firms’ use of true materials” (optional)</td>
</tr>
<tr class="even">
<td>12</td>
<td>“at the margin”</td>
<td>P4 also reports a non-marginal object (break-even at a 17 percent cut)</td>
<td>fine as the main question; optional “near the current rate”</td>
</tr>
</tbody>
</table>
</section>
<section id="suggested-version-minimal-edits" class="level2">
<h2 class="anchored" data-anchor-id="suggested-version-minimal-edits">Suggested version (minimal edits)</h2>
<p>How does tax revenue change as the government changes the sales-tax rate on purchases? As the rate increases, the incentive to claim additional fictitious deductions increases, but more overreporting raises the probability of detection. Therefore, firms face a trade-off. Conversely, a decrease in the rate reduces the incentive to overreport. Firms decrease their overreporting (intensive margin), and some stop overreporting altogether (extensive margin). An increase in the rate also affects firms’ choice of true materials because it lowers the net-of-tax price of materials relative to output. Hence, firms buy more materials and produce more. Larger output raises the tax collected on sales, but more materials lower revenue because claimed deductions rise. How does tax revenue change at the margin for a change in the rate? How much of that change comes from firms overreporting more, and how much from firms buying more materials?</p>
<hr>
</section>
</section>
<section id="proof-read-p3-and-p4-l27-l29-hanss-revision-2026-10-08" class="level1">
<h1>Proof-read: P3 and P4 (L27, L29), Hans’s revision, 2026-10-08</h1>
<section id="p3-l27" class="level2">
<h2 class="anchored" data-anchor-id="p3-l27">P3 (L27)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Where</th>
<th>Issue</th>
<th>Suggestion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>“of which the overreporting response accounts for 0.14 points”</td>
<td>“of which” includes the mechanical 1 point; the increase sentence says “beyond the mechanical 1 percent”. Parallel wording reads faster and is exact</td>
<td>“A 1 percent cut lowers them by about 1.32 percent: beyond the mechanical 1 percent, the overreporting response accounts for 0.14 points and the materials response for 0.18 points.” (optional)</td>
</tr>
</tbody>
</table>
<p>No errors; terms consistent (mechanical effect, materials response, overreporting response).</p>
</section>
<section id="p4-l29" class="level2">
<h2 class="anchored" data-anchor-id="p4-l29">P4 (L29)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Where</th>
<th>Issue</th>
<th>Suggestion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>“at the 95 percent significance level”</td>
<td>Wrong statistical term: 95 percent is the confidence level; the significance level is 5 percent. Also, the claim is about the set: from a cut of about 28 percent the 95 percent confidence set lies above zero (the point estimate is already positive from about 17 percent)</td>
<td>“Net sales-tax revenue turns positive with a cut of about 17 percent, and significantly so, at the 5 percent level, with a cut of about 28 percent or more.” The test is conservative (size at most 5 percent), so “at the 5 percent level” is valid</td>
</tr>
<tr class="even">
<td>3</td>
<td>“would make net sales-tax revenue positive” (cut of 28 percent)</td>
<td>Dropping the 17 percent point estimate leaves the reader with only the set’s edge, which reads as the break-even itself</td>
<td>keep both numbers (see 2)</td>
</tr>
<tr class="odd">
<td>4</td>
<td>“revenue positive”</td>
<td>double space</td>
<td>single space</td>
</tr>
<tr class="even">
<td>5</td>
<td>“… is negative.”</td>
<td>The reader asks “how so?”; P2 defines net revenue, so one clause answers it</td>
<td>optional: “is negative: sales-tax refunds exceed gross sales-tax revenue.”</td>
</tr>
</tbody>
</table>
</section>
<section id="suggested-p4" class="level2">
<h2 class="anchored" data-anchor-id="suggested-p4">Suggested P4</h2>
<p>At the current rate, net sales-tax revenue from firms in the nine industries where the test detects overreporting (<strong>?@sec-testing</strong>) is negative: sales-tax refunds exceed gross sales-tax revenue. A 1 percent increase in the rate lowers net sales-tax revenue by about 1.7 percent of gross sales-tax revenue. Net sales-tax revenue turns positive with a cut of about 17 percent, and significantly so, at the 5 percent level, with a cut of about 28 percent or more. Undetected overreporting costs the government 4.1 percent of gross sales-tax revenue from these firms.</p>
<hr>
</section>
</section>
<section id="proof-read-round-2-p3-and-p4-l27-l29-2026-10-08" class="level1">
<h1>Proof-read round 2: P3 and P4 (L27, L29), 2026-10-08</h1>
<p>Hans: P2 defines net sales-tax revenue, so the reader can see why it is negative; no “how so” clause needed (item 5 above withdrawn).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Where</th>
<th>Issue</th>
<th>Suggestion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>P3, “Materials response accounts for 0.18 points” (cut sentence)</td>
<td>missing article; the increase sentence has “The materials response”</td>
<td>“The materials response accounts for …”</td>
</tr>
<tr class="even">
<td>2</td>
<td>P4, “would make net sales-tax revenue positive at the 5 percent significance level”</td>
<td>“significance level” is now right. “Make … positive at the 5 percent level” reads slightly as the break-even; the claim is that revenue is significantly positive from that cut on</td>
<td>“A cut of about 28 percent or more would make net sales-tax revenue significantly positive, at the 5 percent level.”</td>
</tr>
<tr class="odd">
<td>3</td>
<td>P4 vs abstract</td>
<td>the abstract reports the point break-even (about 17 percent), the opener only the significance edge (about 28 percent); a reader coming from the abstract looks for 17</td>
<td>fine if deliberate; ch.&nbsp;8 Results reports both</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="proof-read-motivation-section-l138-166-hanss-review-edits-2026-10-08" class="level1">
<h1>Proof-read: motivation section (L138-166), Hans’s review edits, 2026-10-08</h1>
<p>Source checked: Perry and Cárdenas (1986), vol.&nbsp;2, pp.&nbsp;143-147 (Lit-Papers PDF, pdftotext), and vol.&nbsp;3, pp.&nbsp;277-278.</p>
<section id="three-channels-paragraph-l150" class="level2">
<h2 class="anchored" data-anchor-id="three-channels-paragraph-l150">Three-channels paragraph (L150)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Where</th>
<th>Issue</th>
<th>Suggestion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>“makes materials cheaper, hence the firm buys more materials, claims …”</td>
<td>“hence” is an adverb, so the comma joins two sentences (comma splice)</td>
<td>“makes materials cheaper, so the firm buys more materials, …”</td>
</tr>
<tr class="even">
<td>2</td>
<td>“Third, when the rate on purchases differs from the rate on sales, the taxes change the price of materials relative to output” (my text, 2026-10-07)</td>
<td>the condition is wrong for this exercise: raising <span class="math inline">\(\tau_P\)</span> alone changes the relative price whether or not the two rates differ at baseline (ch.&nbsp;2: “By changing either rate, the government changes the price of materials relative to output”)</td>
<td>“Third, the rate on purchases changes the net-of-tax price of materials relative to output (<strong>?@sec-model-foc-m</strong>).”</td>
</tr>
</tbody>
</table>
</section>
<section id="enforcement-paragraph-l164" class="level2">
<h2 class="anchored" data-anchor-id="enforcement-paragraph-l164">Enforcement paragraph (L164)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Where</th>
<th>Issue</th>
<th>Suggestion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>3</td>
<td>“Likewise, governments might collect …”</td>
<td>“likewise” means “in the same way”; penalties are a second instrument, not a similar one</td>
<td>“Governments might also collect …” or keep “In addition”</td>
</tr>
<tr class="even">
<td>4</td>
<td>“suffered from lack of resources and auditors”</td>
<td>article missing (“a lack of”). Source (2:143-146): a very precarious administration; no autonomy over staff and supplies; the budget increase the reforms needed was frustrated by austerity from 1976; audit activity fell; strikes in 1975 and 1979 cost staff. “Auditors” is close but the source speaks of staff and audit activity</td>
<td>“the tax administration was weak: it lacked budget and control over its staff, and it audited little”</td>
</tr>
<tr class="odd">
<td>5</td>
<td>“did not applied penalties”</td>
<td>grammar (“did not apply”); and stronger than the source, which says the penalty system was ineffective: some penalties trivial, others too large to be applied, plus recurrent amnesties (2:144-145)</td>
<td>“its penalties were ineffective: some were trivial and others too large to be applied”</td>
</tr>
<tr class="even">
<td>6</td>
<td>“caught infraganti”</td>
<td>Spanish; English would be “red-handed”, but “caught” already says it</td>
<td>drop “infraganti”</td>
</tr>
<tr class="odd">
<td>7</td>
<td>“only had to repay their true liabilities”</td>
<td>not in the cited pages. 2:145, note: from 1974 the only change was interest on amounts in dispute. With trivial penalties, “repay with little or no penalty” is what the source supports</td>
<td>fold into item 5, or cite the source that says it</td>
</tr>
<tr class="even">
<td>8</td>
<td>locator “3:277–278” (added by me, 2026-10-07)</td>
<td>wrong: those pages are the 1974 inaugural speech announcing a fight against evasion, before the sample period</td>
<td>“2:143–146” only</td>
</tr>
<tr class="odd">
<td>9</td>
<td>(context, not an error)</td>
<td>2:146: administrative problems “seem to have affected sales-tax collection much less, despite the relative ‘disadministration’ of this tax”; the weakness evidence is mostly about the income tax. Also 2:146: “greater tolerance of evasion by the government” from 1976. The volume covers up to about 1985; the sample runs to 1991</td>
<td>the wording “tax administration” (not “sales-tax enforcement”) stays within the source</td>
</tr>
</tbody>
</table>
</section>
<section id="suggested-enforcement-paragraph" class="level2">
<h2 class="anchored" data-anchor-id="suggested-enforcement-paragraph">Suggested enforcement paragraph</h2>
<p>In general, governments can also choose the level of enforcement effort, and therefore they can affect <span class="math inline">\(q(\cdot)\)</span>. Governments might also collect additional income by penalizing firms caught evading. I abstract from both because, during the sample period, the Colombian tax administration was weak: it lacked budget and control over its staff, it audited little, and its penalties were ineffective, some trivial and others too large to be applied <span class="citation" data-cites="PerryCardenas1986">[@PerryCardenas1986, 2:143--146]</span>.</p>
<hr>
</section>
</section>
<section id="proof-read-design-section-hanss-revisions-2026-10-08" class="level1">
<h1>Proof-read: Design section, Hans’s revisions, 2026-10-08</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Where</th>
<th>Issue</th>
<th>Suggestion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>eq-counter-e paragraph, “The counterfacutal overreporting”</td>
<td>typo</td>
<td>“counterfactual”</td>
</tr>
<tr class="even">
<td>2</td>
<td>“new overreporting” vs “counterfactual overreporting”</td>
<td>Hans now says “counterfactual”; the first Design paragraph (“gives the new overreporting”) and the decomposition paragraph (“Because the new overreporting”) still say “new”</td>
<td>one term throughout: “counterfactual overreporting”</td>
</tr>
<tr class="odd">
<td>3</td>
<td>auxiliary-parameter paragraph, “… <strong>?@sec-counter-estimation</strong>, therefore these variables cannot be computed”</td>
<td>comma splice (“therefore” is an adverb); “variables” for quantities</td>
<td>“…, so these quantities cannot be computed firm by firm from the data.”</td>
</tr>
<tr class="even">
<td>4</td>
<td>“I invert the test., following <span class="citation" data-cites="AK2020">@AK2020</span>.”</td>
<td>stray period before the comma</td>
<td>“I invert the test, following <span class="citation" data-cites="AK2020">@AK2020</span>.”</td>
</tr>
<tr class="odd">
<td>5</td>
<td>same paragraph, removed sentence “At each <span class="math inline">\(\Delta\)</span>, <span class="math inline">\(\theta\)</span> is fixed at the operating point … and only <span class="math inline">\(\gamma\)</span> is re-optimized”</td>
<td>content: this is the only body statement that the cost parameters <span class="math inline">\(\delta\)</span> are also held fixed and only <span class="math inline">\(\gamma\)</span> moves (Scope says only that <span class="math inline">\((\lambda_1,\bar\lambda)\)</span> is fixed). <span class="citation" data-cites="AK2020">@AK2020</span> is cited for fixing <span class="math inline">\(\theta\)</span> (App. F), not for test inversion, so “following <span class="citation" data-cites="AK2020">@AK2020</span>” now credits them with the wrong thing</td>
<td>restore one sentence: “At each <span class="math inline">\(\Delta\)</span>, the structural parameters <span class="math inline">\(\theta\)</span> stay at the operating point (<strong>?@sec-cf-estimates</strong>) and only <span class="math inline">\(\gamma\)</span> is re-optimized, as in <span class="citation" data-cites="AK2020">@AK2020</span>.”</td>
</tr>
<tr class="even">
<td>6</td>
<td>“<span class="math inline">\(\chi^2_{d_g,1-\alpha}=\}\)</span>”</td>
<td>broken: nothing after “=”; <span class="math inline">\(\alpha\)</span> undefined</td>
<td>“<span class="math inline">\(\chi^2_{18,.95}=28.87\)</span>” (or “<span class="math inline">\(\chi^2_{d_g,.95}\)</span>” without the value)</td>
</tr>
<tr class="odd">
<td>7</td>
<td>revenue-base sentence</td>
<td>fine; with the textbook-elasticity sentence commented out, the reader learns why the base is <span class="math inline">\(|R(0)|\)</span> from the opener (net revenue negative)</td>
<td>none</td>
</tr>
<tr class="even">
<td>8</td>
<td>firms paragraph, “in the nine industries (12,050 firm-years) where the test rejected correct reporting”</td>
<td>the parenthesis splits “industries … where”; tense and term differ from the opener (“where the test detects overreporting”)</td>
<td>“in the nine industries where the test detects overreporting (12,050 firm-years)”</td>
</tr>
<tr class="odd">
<td>9</td>
<td>“A group of corner firms pay no sales tax on their purchases (…) get no credit at any rate”</td>
<td>two finite verbs, no conjunction</td>
<td>“Some corner firms pay no sales tax on their purchases (<span class="math inline">\(\tau_P=0\)</span>; 3,123 firm-years): they get no credit at any rate, so they have no reason to start overreporting.”</td>
</tr>
<tr class="even">
<td>10</td>
<td>“treated as truthful … because the test could not reject truthful reporting”</td>
<td>accuracy: of the other 19 industries, the test was run and did not reject in 8 (311, 312, 332, 341, 381, 382, 383, 390); 323, 356 and 384 have no test result, and 8 more are not tested (<code>1510-test-inversion.csv</code>). A non-rejection is also inconclusive on its own</td>
<td>“are treated as truthful, <span class="math inline">\(M=M^*\)</span> and <span class="math inline">\(e=0\)</span>: the test does not detect overreporting in them, or was not run, so the ex-ante selection rule keeps them out of the structural estimation.”</td>
</tr>
</tbody>
</table>
</section>
<section id="proof-read-estimating-the-model-l199433-hanss-revisions-2026-10-09" class="level1">
<h1>Proof-read: “Estimating the model” (L199–433), Hans’s revisions, 2026-10-09</h1>
<p>Audience: JMP/thesis readers, first-year PhD level. Facts checked against the code and products: the operating fit <code>1616-i-k0.75-kappa0.5</code>, the stage-2 input <code>1598</code>, <code>grid_estimator.cpp</code>, and the log of 2026-10-02/03.</p>
<section id="a.-accuracy-and-notation-fix-before-sending" class="level2">
<h2 class="anchored" data-anchor-id="a.-accuracy-and-notation-fix-before-sending">A. Accuracy and notation (fix before sending)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Line</th>
<th>Text</th>
<th>Issue</th>
<th>Suggestion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A1</td>
<td>229–231</td>
<td>“<span class="math inline">\(\lambda_{0,jt}\)</span> is an scaling parameter …” (definition with <span class="math inline">\(\bar\lambda\)</span> and <span class="math inline">\(\bar M_{j,t-1}\)</span> commented out)</td>
<td><span class="math inline">\(\bar\lambda\)</span> is now never defined, but L327, L366, L403, L433 and the table use it. A reader can’t tell what is estimated or what “level of detection” means</td>
<td>Restore one sentence: “where <span class="math inline">\(\lambda_{0,jt}\equiv1/(\bar\lambda\bar M_{j,t-1})\)</span> and <span class="math inline">\(\bar M_{j,t-1}\)</span> is the mean reported materials of the firm’s industry in the previous year: detection depends on overreporting relative to a typical firm in the industry, <span class="math inline">\(\bar\lambda\)</span> sets its level and <span class="math inline">\(\lambda_1\)</span> its curvature.”</td>
</tr>
<tr class="even">
<td>A2</td>
<td>251</td>
<td>“<span class="math inline">\(\theta=(\lambda_1,\lambda_{0,jt},\delta_0,\delta_1,\delta_2)\)</span>”</td>
<td><span class="math inline">\(\lambda_{0,jt}\)</span> is built from data (<span class="math inline">\(\bar M_{j,t-1}\)</span>) and <span class="math inline">\(\bar\lambda\)</span>; the parameter is <span class="math inline">\(\bar\lambda\)</span></td>
<td>“<span class="math inline">\(\theta=(\lambda_1,\bar\lambda,\delta_0,\delta_1,\delta_2)\)</span>”</td>
</tr>
<tr class="odd">
<td>A3</td>
<td>355, 365</td>
<td>“<span class="math inline">\(\psi\)</span> is independent of <span class="math inline">\((\omega,M,\bar\tau_{P,jt})\)</span>”; row “<span class="math inline">\(\psi\ln\tilde\tau_{P,jt}\)</span>”</td>
<td>The row uses the firm’s own rate, <span class="math inline">\(\ln\tau_{P,it}\)</span> (input column <code>ltau_bar</code> = <span class="math inline">\(\ln\tau_P\)</span> exactly in <code>1598</code>; the old “leave-one-out industry mean” was the robustness file). Also <span class="math inline">\(\tilde\tau_P\)</span> is the counterfactual rate <span class="math inline">\((1+\Delta)\tau_P\)</span> in the Design section</td>
<td>“<span class="math inline">\(\psi\)</span> is independent of <span class="math inline">\((\omega,M,\tau_{P,it})\)</span>”; row “<span class="math inline">\(\psi(M,Z)\ln\tau_{P,it}\)</span>”</td>
</tr>
<tr class="even">
<td>A4</td>
<td>364, 366</td>
<td>rows <span class="math inline">\(\varepsilon\,\partial h/\partial\lambda_1\)</span>, <span class="math inline">\(\varepsilon\,\partial h/\partial\bar\lambda\)</span></td>
<td>The engine uses softsign-bounded scores, <span class="math inline">\(s/(1+|s|)\)</span> (<code>grid_estimator.cpp</code> ~L1207–1209). As written the moment differs from the one estimated</td>
<td>Keep the partial derivatives and add: “the scores enter bounded, <span class="math inline">\(s/(1+|s|)\)</span>, so that rows stay finite near the ceiling (<strong>?@sec-app-elvis</strong>).”</td>
</tr>
<tr class="odd">
<td>A5</td>
<td>367, 371</td>
<td>“<span class="math inline">\(\varepsilon_j(M,Z)\)</span>”; “<span class="math inline">\(E[\varepsilon_j]=0\)</span>”</td>
<td><span class="math inline">\(\varepsilon_j\)</span> reads as a different variable; the rows are <span class="math inline">\(\varepsilon\cdot1\{j\}\)</span>, one per industry</td>
<td>Row “<span class="math inline">\(\varepsilon(M,Z)\,1\{j\},\ j=1,\dots,9\)</span>”; text “<span class="math inline">\(E[\varepsilon\mid j]=0\)</span>”</td>
</tr>
<tr class="even">
<td>A6</td>
<td>371</td>
<td>“matches the overreporting share of true materials <span class="math inline">\(E[\mathcal V_{j}]=E[\ln(1+\tfrac{e_{j}}{M_{j}})]\)</span>, from <strong>?@sec-pf</strong>”</td>
<td><span class="math inline">\(\mathcal V\)</span> comes from the first stage (<strong>?@sec-deconvolution</strong>, as L203 says), not the PF; and <span class="math inline">\(\ln(1+e/M)\)</span> is the log ratio, not the share</td>
<td>“…matches the data’s mean <span class="math inline">\(\mathcal V\)</span> (<strong>?@sec-deconvolution</strong>): <span class="math inline">\(E[u\mid j]=E[\mathcal V\mid j]\)</span>, where <span class="math inline">\(u=\ln(1+e/M)\)</span>.”</td>
</tr>
<tr class="odd">
<td>A7</td>
<td>409, 426</td>
<td>“point estimates found by grid search over <span class="math inline">\((\lambda_1,\bar\lambda)\)</span>”</td>
<td><span class="math inline">\((0.75,0.5)\)</span> is a passing grid point, not the minimizer: the fine grid also passes <span class="math inline">\((0.775,0.5)\)</span> with a lower <span class="math inline">\(TS\)</span> (22.0 vs 23.7), within refit noise (appendix A). Calling it the grid-search estimate overclaims, and the text no longer says which point it is or that <span class="math inline">\(TS=23.7&lt;27.59\)</span></td>
<td>L409: “<strong>?@tbl-cf-estimates</strong> reports the estimates at <span class="math inline">\((\lambda_1,\bar\lambda)=(0.75,0.5)\)</span>, a grid point that passes the conservative test (<span class="math inline">\(TS_n=23.7&lt;\chi^2_{17,.95}=27.59\)</span>); the <span class="math inline">\(\delta\)</span>’s and <span class="math inline">\(\gamma\)</span> are estimated at that point. I fix <span class="math inline">\(\theta\)</span> there for the counterfactual.” Caption: “Estimates at the operating point <span class="math inline">\((\lambda_1,\bar\lambda)=(0.75,0.5)\)</span>, …”</td>
</tr>
<tr class="even">
<td>A8</td>
<td>389</td>
<td>“The moments are combined…”</td>
<td>With “seventeen” and <span class="math inline">\(\chi^2_{17,.95}=27.59\)</span> removed, <span class="math inline">\(d_g\)</span> is never given; the table’s <span class="math inline">\(\chi^2\)</span> row has no value (see A12)</td>
<td>add “Here <span class="math inline">\(d_g=17\)</span> and <span class="math inline">\(\chi^2_{17,.95}=27.59\)</span>.”</td>
</tr>
<tr class="odd">
<td>A9</td>
<td>429</td>
<td>“convex in productivity, since <span class="math inline">\(\hat\delta_1&gt;0\)</span> and <span class="math inline">\(\hat\delta_2&gt;0\)</span>”</td>
<td>Convexity needs only <span class="math inline">\(\hat\delta_2&gt;0\)</span>; <span class="math inline">\(\hat\delta_1&gt;0\)</span> puts the minimum at a positive <span class="math inline">\(\omega\)</span></td>
<td>“convex in productivity (<span class="math inline">\(\hat\delta_2=3.80&gt;0\)</span>), with its minimum at <span class="math inline">\(\hat\omega^*=\hat\delta_1/2\hat\delta_2=3.57\)</span>: the cost falls with productivity up to <span class="math inline">\(\hat\omega^*\)</span> and rises after it.”</td>
</tr>
<tr class="even">
<td>A10</td>
<td>433</td>
<td>“Relative detection risk barely moves with <span class="math inline">\(\kappa\)</span> … at <span class="math inline">\(\bar\lambda=0.5\)</span> and <span class="math inline">\(\bar\lambda=9\)</span>”</td>
<td><span class="math inline">\(\kappa\)</span> is the code name (the text’s <span class="math inline">\(\kappa\)</span> is the cost of evasion). The comparison was between <span class="math inline">\((\lambda_1,\bar\lambda)=(0.75,0.5)\)</span> and <span class="math inline">\((0.70,9)\)</span>, and the second fails the test (<span class="math inline">\(TS\)</span> 29.5). “Relative detection risk” is undefined</td>
<td>“…barely moves with <span class="math inline">\(\bar\lambda\)</span>: a firm’s detection probability relative to its industry mean correlates at 0.87 across industries between <span class="math inline">\((\lambda_1,\bar\lambda)=(0.75,0.5)\)</span> and <span class="math inline">\((0.70,9)\)</span>.”</td>
</tr>
<tr class="odd">
<td>A11</td>
<td>405</td>
<td>12,050 firm-years, no trim mentioned</td>
<td>Fine under the rule “trim stated once in the data section”, but ch.&nbsp;3 does not state it yet, so the count can’t be reproduced from the text</td>
<td>add the trim (and the 5 percent share cut, 369 cap) to the data section now, or keep a footnote here until then</td>
</tr>
<tr class="even">
<td>A12</td>
<td><code>ch08-headline-estimates-table.R</code> L43</td>
<td><code>3"Detection …</code></td>
<td>a stray <code>3</code> makes the script fail; the labels column has 14 entries but the values 12 (<span class="math inline">\(\chi^2\)</span> and “Result” values commented out), so <code>tibble()</code> errors</td>
<td>remove the <code>3</code>; either restore the two values or drop the two labels</td>
</tr>
</tbody>
</table>
</section>
<section id="b.-grammar-and-typos" class="level2">
<h2 class="anchored" data-anchor-id="b.-grammar-and-typos">B. Grammar and typos</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Line</th>
<th>Now</th>
<th>Fix</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>229</td>
<td>“an scaling parameter”; “In this way we can find”</td>
<td>“a scaling parameter”; “I” (the chapter uses the first person singular)</td>
</tr>
<tr class="even">
<td>329</td>
<td>“addresses both nonlinearility and nonseparability, and a parameter-dependant support”</td>
<td>“handles all three: nonlinearity, nonseparability, and a support that depends on the parameters.”</td>
</tr>
<tr class="odd">
<td>337</td>
<td>“<span class="citation" data-cites="Schennach2014">@Schennach2014</span> Theorem 2.1 shows” (renders “Schennach (2014) Theorem 2.1”)</td>
<td>“Theorem 2.1 of <span class="citation" data-cites="Schennach2014">@Schennach2014</span> shows”</td>
</tr>
<tr class="even">
<td>353</td>
<td>“The counterfactual question is equivalent to test that the auxiliary moment condition is compatible with the distribution of unobservable <span class="math inline">\(M\)</span> conditional on the observables <span class="math inline">\(Z\)</span> such that the rest of the moment conditions are satisfied.”</td>
<td>“Estimating a counterfactual quantity is then a test: a candidate value is in the confidence set if some conditional distribution of <span class="math inline">\(M\)</span> given <span class="math inline">\(Z\)</span> satisfies its moment together with all the others.”</td>
</tr>
<tr class="odd">
<td>403</td>
<td>“perfomed”</td>
<td>“performed”</td>
</tr>
<tr class="even">
<td>405</td>
<td>“including the exact objective function can be found in”; “Next section discusses”</td>
<td>“<strong>?@sec-app-elvis</strong> gives the implementation, including the exact objective function. The next section reports the estimates.”</td>
</tr>
<tr class="odd">
<td>426</td>
<td>“where the test reject”; “5 percent significant level”; <span class="math inline">\(E[g(M,X,\hat\theta)]\)</span></td>
<td>“rejects”; “significance level”; <span class="math inline">\(Z\)</span> (the text’s notation)</td>
</tr>
<tr class="even">
<td>429</td>
<td>“imples”</td>
<td>“implies”</td>
</tr>
<tr class="odd">
<td>431</td>
<td>“The implied mean detection probabilities is 6.8 percent (95 percent set …). The median 2.0 percent, …”</td>
<td>“The implied mean detection probability is 6.8 percent (95 percent confidence set 5.7 to 11.0 percent). The median is 2.0 percent, the 80th percentile 18.5 percent, the 90th 27 percent, and the maximum 57 percent.”</td>
</tr>
<tr class="even">
<td>409</td>
<td>“(<span class="math inline">\(E[u]\ge0.05\)</span>)”</td>
<td>per-firm statement: “(<span class="math inline">\(u\ge0.05\)</span>)”</td>
</tr>
</tbody>
</table>
</section>
<section id="c.-structure" class="level2">
<h2 class="anchored" data-anchor-id="c.-structure">C. Structure</h2>
<ul>
<li><strong>L215–217 repeat ch.&nbsp;2</strong> (L77–79, the <span class="citation" data-cites="Carrillo2022">@Carrillo2022</span> pattern and why detection can’t explain the rise), with a different mechanism: here, coordination costs at the top; there, legal avoidance, more to lose and collusion. Two versions of the same argument invite the question of which one the model uses. Suggest replacing both paragraphs with one sentence: “The cost of evasion is convex in productivity, which lets the model reproduce the rise and drop of evasion along the size distribution <strong>?@sec-model</strong>.”</li>
<li><strong>L205</strong> attributes increasing detection to the literature building on <span class="citation" data-cites="Allingham1972">@Allingham1972</span>; in Allingham–Sandmo itself the audit probability is fixed. Ch. 2 names <span class="citation" data-cites="Almunia2018">@Almunia2018</span> as the closest model. Suggest: “As in <span class="citation" data-cites="Almunia2018">@Almunia2018</span> (<strong>?@sec-model</strong>), the probability of detection, <span class="math inline">\(q(e)\)</span>, increases with overreporting.”</li>
<li><strong>L403</strong> (“will be performed as a robustness check”; “<span class="math inline">\(\delta\)</span> behaved well during exploratory analysis”) promises future work and gives an informal assessment in a supervisors’ draft. Suggest dropping the two sentences or moving them to a draft note; the operating-point sentence (A7) carries what the reader needs.</li>
<li><strong>L409</strong> opens the estimates section with fit statistics before the reader has seen the parameters. Suggested order: the operating point and test (A7), the cost function (L429), detection (L431), the level caveat (L433), then fit (E[u] within 0.02 in seven of nine; 331 0.144 vs 0.168, 369 0.551 vs 0.361).</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>