---
title: "Tax Evasion and Productivity"
execute: 
  echo: false
  warning: false
number-sections: true
shift-heading-level-by: -1
format:
  jasa-pdf:
    keep-tex: true
    latex-output-dir: Output
    journal:
      blinded: false
  jasa-html: default
    # html-table-processing: none
  # html: 
  #   theme: pandoc
  # pdf: default
date: today #last-modified
author:
  - name: Hans Martinez
    acknowledgements: | 
      email: hmarti33@uwo.ca. I thank my supervisors Salvador Navarro, David Rivers, and Victor Aguiar for their guidance.
    affiliations:
      - name: University of Western Ontario
        department: Department of Economics
abstract: |
  Corporate tax evasion through cost overreporting spreads internationally causing governments significant tax revenue losses. Detecting and measuring the magnitude of tax evasion remains a challenge, even for the few studies on overreporting where researchers can exploit administrative data. Moreover, if this evasion strategy accounts for economic losses as large as reported, then cost overreporting might bias estimates of production functions, especially productivity. This paper addresses both issues. I first provide a novel strategy to estimate cost overreporting using commonly available firm-level data. I then formally show that ignoring cost overreporting leads to downward biased productivity estimates. Finally, I demonstrate how to recover productivity in the presence of tax evasion.
keywords:
  - Tax Evasion
  - Cost Overreporting
  - Production Function Estimation
  - Productivity
bibliography:
  - biblio/export.bib
  - biblio/export2.bib
  - biblio/export3.bib
  - biblio/export31072022.bib
  - biblio/b100422.bib
  - biblio/b270123.bib
  - biblio/b100424.bib
filters:
  - custom-numbered-blocks
  - latex-environment
custom-numbered-blocks:
  groups:
    thmlike:
      collapse: false
      colors: [99CCFF, FFFFFF]
  classes:
    Theorem:
      group: thmlike
    Proposition:
      group: thmlike
    Assumption:
      group: thmlike
    Definition:
      group: thmlike
environments: anfxnote
commands: fxnote
---
```{r}
#| label: setup
#| echo: false
#| warning: false


library(tidyverse)
library(ggplot2)
library(modeest)
library(fixest)
library(kableExtra)
library(modelsummary)
library(tinytable)
library(stringr)

load("../Code/Products/colombia_data.RData")
load("../Code/Products/global_vars.RData")
load("../Code/Products/intermediates.RData")
options(knitr.kable.NA = '')

# The style of the table
# my_style = style.tex("aer", model.format = "(i)")

# markdown = TRUE is only useful in Rmarkdown documents
setFixest_etable(markdown = TRUE)

setFixest_dict(c(
    share_sales_tax = "Sales Tax Rate",
    `relevel(factor(juridical_organization),ref="3")0` = "Proprietorships",
    `relevel(factor(juridical_organization),ref="3")1` = "Ld. Liability Co.",
    `relevel(factor(juridical_organization),ref="3")2` = "Collective",
    `relevel(factor(juridical_organization),ref="3")3` = "Corporation",
    `relevel(factor(juridical_organization),ref="3")4` = "De Facto Corp.",
    `relevel(factor(juridical_organization),ref="3")5` = "Joint Partnership",
    `relevel(factor(juridical_organization),ref="3")6` = "Joint Stock Co.",
    `relevel(factor(juridical_organization),ref="3")7` = "Cooperative",
    `relevel(factor(juridical_organization),ref="3")8` = "Official Entity",
    `relevel(factor(juridical_organization),ref="3")9` = "Religious Comm.",
    `polym(m,k,l,degree=2,raw=TRUE)1.0.0` = "\\(m\\)",
    `polym(m,k,l,degree=2,raw=TRUE)2.0.0` = "\\(m^2\\)",
    `polym(m,k,l,degree=2,raw=TRUE)0.1.0` = "\\(k\\)",
    `polym(m,k,l,degree=2,raw=TRUE)0.2.0` = "\\(k^2\\)",
    `polym(m,k,l,degree=2,raw=TRUE)0.0.1` = "\\(l\\)",
    `polym(m,k,l,degree=2,raw=TRUE)0.0.2` = "\\(l^2\\)",
    `polym(m,k,l,degree=2,raw=TRUE)1.1.0` = "\\(mk\\)",
    `polym(m,k,l,degree=2,raw=TRUE)1.0.1` = "\\(ml\\)",
    `polym(m,k,l,degree=2,raw=TRUE)0.1.1` = "\\(kl\\)",
    log_share = "Interm.",
    sic_3 = "Industry",
    year = "Year",
    `log(consumed_energy/sales)` = "\\(log(Energy/Revenue)\\)",
    `log(mats_serv/sales)` = "Mats+Serv",
    `log(mats_deduct_share)` = "Mats+Deduc",
    `log(materials/sales)` = "Materials",
    `log(deductibles/sales)` = "Log Share of Deductibles",
    metro_area_code = "Metro Area",
    `factor(fiscal_period)83` = "84-86 F.P.",
    `factor(fiscal_period)86` = "87-91 F.P.",
    capital_share = "Capital",
    consumed_energy_share = "Energy",
    materials_share = "Materials",
    skilled_wage_bill_share = "Skilled Labor",
    unskilled_wage_bill_share = "Unskilled Labor",
    total_expenses_share = "Total Expenditure",
    serv_share_exp = "Services",
    inds_exp_share_exp = "Industrial Expenditure",
    deductible_expenses_share_exp = "Deductible Expenditure",
    CorpOther = "Non-Corporation",
    `factor(year)82`= "Year 82",
    `factor(year)83`= "Year 83",
    `factor(year)84`= "Year 84",
    `factor(year)85`= "Year 85",
    `factor(year)86`= "Year 86",
    `factor(year)87`= "Year 87",
    `factor(year)88`= "Year 88",
    `factor(year)89`= "Year 89",
    `factor(year)90`= "Year 90",
    `factor(year)91`= "Year 91",
    JO_classProprietorship = "Proprietorship",
    JO_classLtd.Co. = "LLC",
    JO_classPartnership = "Partnership",
    juridical_organizationLLCs = "LLC",
    juridical_organizationProprietorships = "Proprietorship",
    `treatNon-Corp` = "Non-Corp.",
    year83 = "1983",
    year84 = "1984",
    year85 = "1985",
    year86 = "1986",
    `treat_3increased`="Increment",
    `treat_3exempt`="Exempt",
    `treat_3nochange`="No Change",
    `log(services_exp_share)` = "Services",
    `log(industrial_exp_share)` = "Industrial",
    `log(deductible_exp_share)` = "Deductibles"#,
    # `year81:treatNon-Corp:treat_3tax_treat` = "81",
    # `year82:treatNon-Corp:treat_3tax_treat` = "82",
    # `year84:treatNon-Corp:treat_3tax_treat` = "84",
    # `year85:treatNon-Corp:treat_3tax_treat` = "85",
    # `year86:treatNon-Corp:treat_3tax_treat` = "86",
    # `year87:treatNon-Corp:treat_3tax_treat` = "87",
    # `year88:treatNon-Corp:treat_3tax_treat` = "88",
    # `year89:treatNon-Corp:treat_3tax_treat` = "89",
    # `year90:treatNon-Corp:treat_3tax_treat` = "90",
    # `year91:treatNon-Corp:treat_3tax_treat` = "91"
    # "note 1" = "Reference group is J.O. (9) in 1981. Production Function Polynomial and interactions not displayed.",
    # "note 2" = "Reference group is J.O. (9) in Fiscal Period 1981-1983. Only interactions displayed."
))


# colombia_data_frame <- colombia_data_frame %>%
#     ungroup() %>%
#     left_join(jo_class, by = join_by( juridical_organization == JO_code))

```


## Updates {-}

- Tax Evasion and Productivity: Using PF to identify tax evasion through input overreporting
  - CD
    - Preliminary results of Tax Evasion: Moments, MLE (Truncated Normal and LogNormal)
    - **New** Identification of PF parameters when $h$ is polynomial
    - Preliminary results of PF parameters
    - **New** Productivity results
  - TransLog
    - Identification strategy for tax evasion

- Leveraging Tax Policy change to identify changes in tax evasion
  - Why? Relax common technology assumption
  - Triple difference identification strategy (with CD)

## Next Steps {-}

- Tax Evasion and Productivity
  - Back of Envelope estimates for Gov Losses in Tax Revenue
  - App of Productivity: Aggregate Productivity and Resource Misallocations
  - Translog results
  - Non-parametric Deconvolution
  - Non-parametric PF
- DiD
  - Relaxing parallel trends: Linear trends that in the absence of policy change would have continued



<!-- Intro -->
<!-- {{< include sections/10-intro.rmd >}} -->

<!-- Theoretical Model *-->
{{< include sections/45-model.qmd >}}

<!-- Setting -->
<!-- {{< include sections/35-setting.qmd >}} -->

<!-- Identification strategy
<!-- {{< include sections/55-id-strat.qmd >}} -->

<!-- Colombia 1981-1991: tax system and reforms *-->
{{< include sections/80-colombia.qmd >}}

<!-- Colombia 1981-1991: data *-->
{{< include sections/90-colombia-data.qmd >}}

<!-- Colombia 1981-1991: an application -->
{{< include sections/95-colombia-empiric2.qmd >}}

<!-- Relative Prices -->
{{< include sections/125-prices.qmd >}}

<!-- Same Techonology *-->
{{< include sections/92-col-corp-tech.qmd >}}

<!-- Identification strategy *-->
{{< include sections/56-id-evasion.qmd >}}

<!-- Revenue Misreporting *-->
<!-- {{< include sections/110-revenue.qmd >}} -->

<!-- Implementation -->
{{< include sections/120-implementation.qmd >}}

<!-- Implementation -->
{{< include sections/150-intermediates.qmd >}}

<!-- Deconvolution -->
{{< include sections/200-deconv.qmd >}}

{{< include sections/250-pf.qmd >}}

<!-- Misallocation -->
{{< include sections/300-misallocation.qmd >}}

## References {.appendix}

::: {#refs}
:::


<!-- {{< include sections/100-appendix.qmd >}} -->



